include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance Rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Best Practices
    prefer_final_locals: true
    unnecessary_this: true
    avoid_print: true
    annotate_overrides: true
