import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:mobile/core/models/models.dart';

class AdSpecifications extends StatelessWidget {
  final AdWithDetails ad;

  const AdSpecifications({super.key, required this.ad});

  @override
  Widget build(BuildContext context) {
    if (ad.attributes == null || ad.attributes!.isEmpty) {
      return const SizedBox.shrink();
    }

    final specs = ad.attributes!.entries
        .where((e) => e.value != null && e.value.toString().isNotEmpty)
        .toList();

    if (specs.isEmpty) return const SizedBox.shrink();

    final isNe = context.locale.languageCode == 'ne';

    return Container(
      margin: const EdgeInsets.fromLTRB(16, 8, 16, 24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey[200]!),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 4),
            child: Text(
              isNe ? 'विशेषताहरू' : "Specifications",
              style: GoogleFonts.inter(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: const Color(0xFF1F2937),
              ),
            ),
          ),
          const Divider(height: 16, color: Color(0xFFF3F4F6)),
          ListView.separated(
            physics: const NeverScrollableScrollPhysics(),
            shrinkWrap: true,
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            itemCount: specs.length,
            separatorBuilder: (_, __) => Padding(
              padding: const EdgeInsets.symmetric(vertical: 12),
              child: Divider(height: 1, color: Colors.grey[100]),
            ),
            itemBuilder: (context, index) {
              final entry = specs[index];
              return Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    isNe ? _localizedKey(entry.key) : _formatKey(entry.key),
                    style: GoogleFonts.inter(
                      fontSize: 14,
                      fontWeight: FontWeight.w400,
                      color: const Color(0xFF6B7280),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Flexible(
                    child: Text(
                      isNe ? _localizedValue(entry.value.toString()) : entry.value.toString(),
                      textAlign: TextAlign.end,
                      style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: const Color(0xFF111827),
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ],
      ),
    );
  }

  String _formatKey(String key) {
    if (key.isEmpty) return key;
    final formatted = key.replaceAll('_', ' ');
    return formatted[0].toUpperCase() +
        formatted.substring(1).replaceAllMapped(
            RegExp(r'[A-Z]'), (m) => ' ${m[0]}');
  }

  String _localizedKey(String key) => _keyMapNe[key] ?? _formatKey(key);

  String _localizedValue(String value) => _valueMapNe[value] ?? value;

  static const _keyMapNe = {
    'condition': 'अवस्था',
    'brand': 'ब्रान्ड',
    'model': 'मोडेल',
    'warranty': 'वारेन्टी',
    'color': 'रङ',
    'storage': 'भण्डारण क्षमता',
    'ram': 'र्‍याम',
    'batteryHealth': 'ब्याट्री स्वास्थ्य',
    'processor': 'प्रोसेसर',
    'graphics': 'ग्राफिक्स कार्ड',
    'screenResolution': 'स्क्रिन रिजोलुसन',
    'screenSize': 'स्क्रिन साइज',
    'smartFeatures': 'स्मार्ट सुविधाहरू',
    'megapixels': 'मेगापिक्सेल',
    'year': 'निर्माण वर्ष',
    'mileage': 'माइलेज/कि.मी.',
    'fuelType': 'इन्धन प्रकार',
    'transmission': 'ट्रान्समिसन',
    'engineCapacity': 'इन्जिन क्षमता (cc)',
    'owners': 'मालिक संख्या',
    'registrationYear': 'दर्ता वर्ष',
    'registrationLocation': 'दर्ता स्थान',
    'seats': 'सिट संख्या',
    'bicycleType': 'साइकल प्रकार',
    'totalArea': 'कुल क्षेत्रफल',
    'areaUnit': 'क्षेत्रफल एकाइ',
    'bedrooms': 'शयनकोठा',
    'bathrooms': 'स्नानकोठा',
    'furnishing': 'फर्निचर अवस्था',
    'parking': 'पार्किङ स्थान',
    'floorNumber': 'तल्ला नम्बर',
    'totalFloors': 'भवनमा कुल तल्ला',
    'facing': 'मुख दिशा',
    'propertyAge': 'सम्पत्ति उमेर',
    'amenities': 'सुविधाहरू',
    'roadAccess': 'सडक पहुँच',
    'roadWidth': 'सडक चौडाइ',
    'monthlyRent': 'मासिक भाडा',
    'securityDeposit': 'धरौटी',
    'availableFrom': 'उपलब्ध मिति',
    'clothingType': 'लुगा प्रकार',
    'size': 'साइज',
    'fitType': 'फिट प्रकार',
    'sleeveType': 'बाहुला प्रकार',
    'footwearType': 'जुत्ता प्रकार',
    'shoeSize': 'जुत्ता साइज',
    'watchType': 'घडी प्रकार',
    'strapMaterial': 'स्ट्र्याप सामग्री',
    'animalType': 'जनावर प्रकार',
    'vaccination': 'खोप अवस्था',
    'papers': 'कागजात',
    'trained': 'प्रशिक्षित',
    'friendlyWith': 'मैत्रीपूर्ण',
    'productType': 'उत्पादन प्रकार',
    'suitableFor': 'उपयुक्त',
    'experience': 'अनुभव',
    'availability': 'उपलब्धता',
    'languages': 'भाषा ज्ञान',
    'subjects': 'विषय',
    'gradeLevel': 'कक्षा/तह',
    'modeOfTeaching': 'पढाउने तरिका',
    'companyName': 'कम्पनीको नाम',
    'jobType': 'जागिर प्रकार',
    'experienceRequired': 'आवश्यक अनुभव',
    'educationRequired': 'आवश्यक शिक्षा',
    'furnitureType': 'फर्निचर प्रकार',
    'material': 'सामग्री',
    'dimensions': 'आयाम (ल × चौ × उ)',
    'assemblyRequired': 'जडान आवश्यक',
    'seatingCapacity': 'बस्ने क्षमता',
    'storageAvailable': 'भण्डारण उपलब्ध',
    'style': 'शैली',
    'sportType': 'खेलकुद प्रकार',
    'instrumentType': 'बाजा प्रकार',
    'machineryType': 'मेसिनरी प्रकार',
    'powerSource': 'शक्ति स्रोत',
    'quantity': 'उपलब्ध मात्रा',
    'expiryDate': 'म्याद सकिने मिति',
    'cropType': 'बाली/बिरुवा प्रकार',
    'farmingToolType': 'कृषि औजार प्रकार',
  };

  static const _valueMapNe = {
    // Condition
    'Brand New': 'नयाँ',
    'Refurbished': 'रिफर्बिस्ड',
    'Used': 'पुरानो',
    // Warranty
    'No Warranty': 'वारेन्टी छैन',
    'Under Warranty (< 6 months)': 'वारेन्टी अन्तर्गत (< ६ महिना)',
    'Under Warranty (6-12 months)': 'वारेन्टी अन्तर्गत (६-१२ महिना)',
    'Under Warranty (1+ years)': 'वारेन्टी अन्तर्गत (१+ वर्ष)',
    // Vehicles
    'Petrol': 'पेट्रोल',
    'Diesel': 'डिजेल',
    'Electric': 'इलेक्ट्रिक',
    'Hybrid': 'हाइब्रिड',
    'CNG': 'सीएनजी',
    'LPG': 'एलपीजी',
    'Manual': 'म्यानुअल',
    'Automatic': 'अटोम्याटिक',
    'Semi-Automatic': 'सेमी-अटोम्याटिक',
    '1st Owner': 'पहिलो मालिक',
    '2nd Owner': 'दोस्रो मालिक',
    '3rd Owner': 'तेस्रो मालिक',
    '4th Owner or More': 'चौथो वा बढी',
    'Sedan': 'सेडान',
    'SUV': 'एसयुभी',
    'Hatchback': 'ह्याचब्याक',
    'Coupe': 'कुपे',
    'Convertible': 'कन्भर्टिबल',
    'Pickup': 'पिकअप',
    'Van': 'भ्यान',
    'Mountain Bike': 'माउन्टेन बाइक',
    'Road Bike': 'रोड बाइक',
    'Kids Bike': 'बच्चाको साइकल',
    // Property
    'sq ft': 'वर्ग फिट',
    'aana': 'आना',
    'ropani': 'रोपनी',
    'sq meter': 'वर्ग मिटर',
    'Studio': 'स्टुडियो',
    'Fully Furnished': 'पूर्ण फर्निचर',
    'Semi Furnished': 'आंशिक फर्निचर',
    'Unfurnished': 'फर्निचर बिना',
    'None': 'छैन',
    'North': 'उत्तर',
    'South': 'दक्षिण',
    'East': 'पूर्व',
    'West': 'पश्चिम',
    'North-East': 'उत्तर-पूर्व',
    'North-West': 'उत्तर-पश्चिम',
    'South-East': 'दक्षिण-पूर्व',
    'South-West': 'दक्षिण-पश्चिम',
    'Under Construction': 'निर्माणाधीन',
    '0-1 years': '०-१ वर्ष',
    '1-5 years': '१-५ वर्ष',
    '5-10 years': '५-१० वर्ष',
    '10-20 years': '१०-२० वर्ष',
    '20+ years': '२०+ वर्ष',
    'Lift/Elevator': 'लिफ्ट',
    'Power Backup': 'पावर ब्याकअप',
    'Water Supply': 'पानी आपूर्ति',
    'Security/Gated': 'सुरक्षा/गेटेड',
    'Gym': 'जिम',
    'Swimming Pool': 'स्विमिङ पुल',
    'Garden': 'बगैंचा',
    'Playground': 'खेल मैदान',
    'Club House': 'क्लब हाउस',
    'Visitor Parking': 'आगन्तुक पार्किङ',
    'Residential': 'आवासीय',
    'Commercial': 'व्यापारिक',
    'Agricultural': 'कृषि',
    'Industrial': 'औद्योगिक',
    'Mixed Use': 'मिश्रित',
    'Paved Road': 'पक्की सडक',
    'Graveled Road': 'ग्राभेल सडक',
    'Dirt Road': 'कच्ची सडक',
    'No Direct Access': 'प्रत्यक्ष पहुँच छैन',
    'Immediately': 'तुरुन्तै',
    '15 days': '१५ दिन',
    '1 month': '१ महिना',
    '2 months': '२ महिना',
    '3 months': '३ महिना',
    // Fashion
    'Free Size': 'फ्री साइज',
    'Shirt': 'सर्ट',
    'T-Shirt': 'टी-सर्ट',
    'Pants': 'प्यान्ट',
    'Jeans': 'जिन्स',
    'Dress': 'ड्रेस',
    'Saree': 'साडी',
    'Kurta': 'कुर्ता',
    'Jacket': 'ज्याकेट',
    'Coat': 'कोट',
    'Sweater': 'स्वेटर',
    'Skirt': 'स्कर्ट',
    'Shorts': 'सर्ट्स',
    'Regular Fit': 'रेगुलर फिट',
    'Slim Fit': 'स्लिम फिट',
    'Loose Fit': 'लुज फिट',
    'Skinny Fit': 'स्किनी फिट',
    'Full Sleeve': 'पूरा बाहुला',
    'Half Sleeve': 'आधा बाहुला',
    'Sleeveless': 'बाहुला बिना',
    '3/4 Sleeve': '३/४ बाहुला',
    'Sneakers': 'स्निकर्स',
    'Formal Shoes': 'औपचारिक जुत्ता',
    'Sandals': 'सेन्डल',
    'Slippers': 'चप्पल',
    'Boots': 'बुट',
    'Heels': 'हिल',
    'Flats': 'फ्ल्याट',
    'Sports Shoes': 'खेलकुद जुत्ता',
    'Analog': 'एनालग',
    'Digital': 'डिजिटल',
    'Smart Watch': 'स्मार्ट वाच',
    'Chronograph': 'क्रोनोग्राफ',
    'Leather': 'छाला',
    'Metal': 'धातु',
    'Rubber': 'रबर',
    'Fabric': 'कपडा',
    // Pets
    'Dog': 'कुकुर',
    'Cat': 'बिरालो',
    'Bird': 'चरा',
    'Fish': 'माछा',
    'Rabbit': 'खरायो',
    'Hamster': 'ह्यामस्टर',
    'Guinea Pig': 'गिनी पिग',
    'Cow': 'गाई',
    'Buffalo': 'भैंसी',
    'Goat': 'बाख्रा',
    'Chicken': 'कुखुरा',
    'Duck': 'हाँस',
    'Other': 'अन्य',
    '0-3 months': '०-३ महिना',
    '3-6 months': '३-६ महिना',
    '6-12 months': '६-१२ महिना',
    '1-2 years': '१-२ वर्ष',
    '2-5 years': '२-५ वर्ष',
    '5+ years': '५+ वर्ष',
    'Male': 'भाले',
    'Female': 'पोथी',
    'Unknown': 'थाहा छैन',
    'Fully Vaccinated': 'पूर्ण खोप लगाइएको',
    'Partially Vaccinated': 'आंशिक खोप',
    'Not Vaccinated': 'खोप नलगाइएको',
    'Yes - All Papers': 'छ - सबै कागजात',
    'Some Papers': 'केही कागजात',
    'No Papers': 'कागजात छैन',
    'Fully Trained': 'पूर्ण प्रशिक्षित',
    'Partially Trained': 'आंशिक प्रशिक्षित',
    'Not Trained': 'प्रशिक्षित छैन',
    'Children': 'बच्चाहरू',
    'Other Dogs': 'अन्य कुकुर',
    'Cats': 'बिरालो',
    'Strangers': 'अपरिचित',
    'Food': 'खाना',
    'Toy': 'खेलौना',
    'Cage': 'पिंजरा',
    'Leash': 'पट्टा',
    'Collar': 'कलर',
    'Grooming': 'ग्रुमिङ',
    'Medicine': 'औषधि',
    'Bedding': 'ओछ्यान',
    'Dogs': 'कुकुर',
    'Birds': 'चरा',
    'All Pets': 'सबै पालतु',
    // Services & Jobs
    'Less than 1 year': '१ वर्ष भन्दा कम',
    '1-3 years': '१-३ वर्ष',
    '3-5 years': '३-५ वर्ष',
    '10+ years': '१०+ वर्ष',
    'Weekdays': 'हप्ताको दिन',
    'Weekends': 'शनिबार/आइतबार',
    'Evenings': 'साँझ',
    '24/7': '२४/७',
    'On-Call': 'कलमा',
    'At Customer Location': 'ग्राहकको स्थानमा',
    'At Provider Location': 'प्रदायकको स्थानमा',
    'Remote/Online': 'रिमोट/अनलाइन',
    'English': 'अंग्रेजी',
    'Nepali': 'नेपाली',
    'Hindi': 'हिन्दी',
    'Newari': 'नेवारी',
    'Full Time': 'पूर्णकालीन',
    'Part Time': 'अंशकालीन',
    'Contract': 'करार',
    'Freelance': 'फ्रिल्यान्स',
    'Internship': 'इन्टर्नशिप',
    'Fresher': 'फ्रेसर',
    'No Formal Education': 'औपचारिक शिक्षा छैन',
    'SLC/SEE': 'एसएलसी/एसईई',
    '+2': '+२',
    "Bachelor's": 'स्नातक',
    "Master's": 'स्नातकोत्तर',
    'PhD': 'पीएचडी',
    'Below 20,000': '२०,००० भन्दा कम',
    'Negotiable': 'मोलमोलाई योग्य',
    // Teaching
    'Math': 'गणित',
    'Science': 'विज्ञान',
    'Social Studies': 'सामाजिक अध्ययन',
    'Computer': 'कम्प्युटर',
    'Accounts': 'लेखा',
    'All Subjects': 'सबै विषय',
    'Primary (1-5)': 'प्राथमिक (१-५)',
    'Secondary (6-10)': 'माध्यमिक (६-१०)',
    '+2/Intermediate': '+२/मध्यवर्ती',
    'Bachelor': 'स्नातक',
    'Master': 'स्नातकोत्तर',
    'Home Tuition': 'घर ट्युसन',
    'Online': 'अनलाइन',
    'At Institute': 'संस्थामा',
    'Group Class': 'सामूहिक कक्षा',
    // Furniture & General
    'Bed': 'बेड',
    'Sofa': 'सोफा',
    'Table': 'टेबल',
    'Chair': 'कुर्सी',
    'Wardrobe': 'अलमारी',
    'Shelf': 'शेल्फ',
    'Desk': 'डेस्क',
    'Cabinet': 'क्याबिनेट',
    'Dining Set': 'डाइनिङ सेट',
    'Wood': 'काठ',
    'Plastic': 'प्लास्टिक',
    'Glass': 'गिलास',
    'Mixed Materials': 'मिश्रित',
    'Yes - Assembly Required': 'हो - जोड्ने आवश्यक',
    'No - Ready to Use': 'छैन - प्रयोगको लागि तयार',
    'Partial Assembly': 'आंशिक जोड्ने',
    '1 Person': '१ जना',
    '2-3 People': '२-३ जना',
    '4-6 People': '४-६ जना',
    '6-8 People': '६-८ जना',
    '8+ People': '८+ जना',
    'Yes': 'छ',
    'No': 'छैन',
    'Modern': 'आधुनिक',
    'Traditional': 'परम्परागत',
    'Vintage': 'पुरानो',
    'Minimalist': 'न्यूनतम',
    'Contemporary': 'समकालीन',
    'Rustic': 'ग्रामीण',
    // Machinery & Agriculture
    'Construction': 'निर्माण',
    'Manufacturing': 'उत्पादन',
    'Office Equipment': 'कार्यालय उपकरण',
    'Medical Equipment': 'चिकित्सा उपकरण',
    'Battery': 'ब्याट्री',
    'Solar': 'सोलार',
    'Food Item': 'खाद्य पदार्थ',
    'Household Item': 'घरायसी सामान',
    'Baby Product': 'बच्चा उत्पादन',
    'Healthcare': 'स्वास्थ्य',
    'Tractor': 'ट्र्याक्टर',
    'Plough': 'हलो',
    'Harvester': 'हार्भेस्टर',
    'Sprayer': 'स्प्रेयर',
    'Hand Tool': 'हात औजार',
  };
}
