-- ============================================
-- POPULATE NEPALI NAMES FOR LOCATIONS
-- ============================================

UPDATE locations SET name_ne = 'Naxal' WHERE id = 71166;
UPDATE locations SET name_ne = 'Gairidhara' WHERE id = 71167;
UPDATE locations SET name_ne = 'Teku' WHERE id = 71168;
UPDATE locations SET name_ne = 'Kamal Pokhari' WHERE id = 71169;
UPDATE locations SET name_ne = 'Sankha Kriti Maha Bihar' WHERE id = 71170;
UPDATE locations SET name_ne = 'Lazimpat' WHERE id = 71171;
UPDATE locations SET name_ne = 'Thamel Marg' WHERE id = 71172;
UPDATE locations SET name_ne = 'Hotel Area' WHERE id = 71173;
UPDATE locations SET name_ne = 'Maharajgunj' WHERE id = 71174;
UPDATE locations SET name_ne = 'Shree Gopal Marg' WHERE id = 71175;
UPDATE locations SET name_ne = 'Balaju' WHERE id = 71176;
UPDATE locations SET name_ne = 'Baluwatar' WHERE id = 71177;
UPDATE locations SET name_ne = 'Chappal Karkhana' WHERE id = 71178;
UPDATE locations SET name_ne = 'Chundevi' WHERE id = 71179;
UPDATE locations SET name_ne = 'Dhumbarahi' WHERE id = 71180;
UPDATE locations SET name_ne = 'Hadigaun' WHERE id = 71181;
UPDATE locations SET name_ne = 'Kapan' WHERE id = 71182;
UPDATE locations SET name_ne = 'Chapali Bhadrakali' WHERE id = 71183;
UPDATE locations SET name_ne = 'Bouddha' WHERE id = 71184;
UPDATE locations SET name_ne = 'Bauddha Stupa area' WHERE id = 71185;
UPDATE locations SET name_ne = 'Boudhanath Marg' WHERE id = 71186;
UPDATE locations SET name_ne = 'Mitrapark' WHERE id = 71187;
UPDATE locations SET name_ne = 'Chhauni' WHERE id = 71188;
UPDATE locations SET name_ne = 'Ghattekulo' WHERE id = 71189;
UPDATE locations SET name_ne = 'Pashupati area' WHERE id = 71190;
UPDATE locations SET name_ne = 'Pashupatinath Marg' WHERE id = 71191;
UPDATE locations SET name_ne = 'Gaushala' WHERE id = 71192;
UPDATE locations SET name_ne = 'Sinamangal' WHERE id = 71193;
UPDATE locations SET name_ne = 'Jagadihel' WHERE id = 71194;
UPDATE locations SET name_ne = 'Baneshwor' WHERE id = 71195;
UPDATE locations SET name_ne = 'New Baneshwor' WHERE id = 71196;
UPDATE locations SET name_ne = 'Sajha Marg' WHERE id = 71197;
UPDATE locations SET name_ne = 'Tripureshwor' WHERE id = 71198;
UPDATE locations SET name_ne = 'Putalisadak' WHERE id = 71199;
UPDATE locations SET name_ne = 'Gairigaon' WHERE id = 71200;
UPDATE locations SET name_ne = 'Kuleshwor' WHERE id = 71201;
UPDATE locations SET name_ne = 'Kalimati' WHERE id = 71202;
UPDATE locations SET name_ne = 'Sorhakhutte' WHERE id = 71203;
UPDATE locations SET name_ne = 'Tangal' WHERE id = 71204;
UPDATE locations SET name_ne = 'Kalanki' WHERE id = 71205;
UPDATE locations SET name_ne = 'Gongabu' WHERE id = 71206;
UPDATE locations SET name_ne = 'Samakhusi' WHERE id = 71207;
UPDATE locations SET name_ne = 'Dallu' WHERE id = 71208;
UPDATE locations SET name_ne = 'Chabahil' WHERE id = 71209;
UPDATE locations SET name_ne = 'Swayambhu Marg' WHERE id = 71210;
UPDATE locations SET name_ne = 'Bagbazaar extension' WHERE id = 71211;
UPDATE locations SET name_ne = 'Jawalakhel' WHERE id = 71212;
UPDATE locations SET name_ne = 'Satdobato' WHERE id = 71213;
UPDATE locations SET name_ne = 'Maitighar' WHERE id = 71214;
UPDATE locations SET name_ne = 'Durbar Marg vicinity' WHERE id = 71215;
UPDATE locations SET name_ne = 'Yatkha' WHERE id = 71216;
UPDATE locations SET name_ne = 'Swayambhu' WHERE id = 71217;
UPDATE locations SET name_ne = 'Bansbari marginal areas' WHERE id = 71218;
UPDATE locations SET name_ne = 'Gagal Pati' WHERE id = 71219;
UPDATE locations SET name_ne = 'Narayan Gopal Chowk' WHERE id = 71220;
UPDATE locations SET name_ne = 'Gyaneshwar' WHERE id = 71221;
UPDATE locations SET name_ne = 'Rabi Bhawan area' WHERE id = 71222;
UPDATE locations SET name_ne = 'Lainchaur' WHERE id = 71223;
UPDATE locations SET name_ne = 'New Road fringes' WHERE id = 71224;
UPDATE locations SET name_ne = 'Kathmandu Durbar Square side' WHERE id = 71225;
UPDATE locations SET name_ne = 'New Road' WHERE id = 71226;
UPDATE locations SET name_ne = 'Indra Chowk' WHERE id = 71227;
UPDATE locations SET name_ne = 'Asan' WHERE id = 71228;
UPDATE locations SET name_ne = 'Durbarmarg' WHERE id = 71229;
UPDATE locations SET name_ne = 'Thamel' WHERE id = 71230;
UPDATE locations SET name_ne = 'Chhaya Devi area' WHERE id = 71231;
UPDATE locations SET name_ne = 'Kamaladi' WHERE id = 71232;
UPDATE locations SET name_ne = 'Dhhetrapati' WHERE id = 71233;
UPDATE locations SET name_ne = 'Ason side' WHERE id = 71234;
UPDATE locations SET name_ne = 'Hattisar' WHERE id = 71235;
UPDATE locations SET name_ne = 'Sundhara' WHERE id = 71236;
UPDATE locations SET name_ne = 'Jamal vicinity' WHERE id = 71237;
UPDATE locations SET name_ne = 'Anamnagar' WHERE id = 71238;
UPDATE locations SET name_ne = 'Maitighar extension' WHERE id = 71239;
UPDATE locations SET name_ne = 'Indrachowk' WHERE id = 71240;
UPDATE locations SET name_ne = 'Putalisadak backstreets' WHERE id = 71241;
UPDATE locations SET name_ne = 'Dilli Bazaar' WHERE id = 71242;
UPDATE locations SET name_ne = 'Bagbazaar' WHERE id = 71243;
UPDATE locations SET name_ne = 'Jyapati' WHERE id = 71244;
UPDATE locations SET name_ne = 'Teku extension' WHERE id = 71245;
UPDATE locations SET name_ne = 'Koteshwor' WHERE id = 71246;
UPDATE locations SET name_ne = 'Balkhu' WHERE id = 71247;
UPDATE locations SET name_ne = 'Thapathali outskirts' WHERE id = 71248;
UPDATE locations SET name_ne = 'Koteshwor Mahadevsthan' WHERE id = 71249;
UPDATE locations SET name_ne = 'Sankhamul' WHERE id = 71250;
UPDATE locations SET name_ne = 'Buspark(Kathmandu)' WHERE id = 71252;
UPDATE locations SET name_ne = 'भोजपुर' WHERE id = 101;
UPDATE locations SET name_ne = 'धनकुटा' WHERE id = 102;
UPDATE locations SET name_ne = 'इलाम' WHERE id = 103;
UPDATE locations SET name_ne = 'झापा' WHERE id = 104;
UPDATE locations SET name_ne = 'खोटाङ' WHERE id = 105;
UPDATE locations SET name_ne = 'मोरङ' WHERE id = 106;
UPDATE locations SET name_ne = 'ओखलढुङ्गा' WHERE id = 107;
UPDATE locations SET name_ne = 'पाँचथर' WHERE id = 108;
UPDATE locations SET name_ne = 'सङ्खुवासभा' WHERE id = 109;
UPDATE locations SET name_ne = 'सोलुखुम्बु' WHERE id = 110;
UPDATE locations SET name_ne = 'सुनसरी' WHERE id = 111;
UPDATE locations SET name_ne = 'ताप्लेजुङ' WHERE id = 112;
UPDATE locations SET name_ne = 'तेह्रथुम' WHERE id = 113;
UPDATE locations SET name_ne = 'उदयपुर' WHERE id = 114;
UPDATE locations SET name_ne = 'बारा' WHERE id = 201;
UPDATE locations SET name_ne = 'धनुषा' WHERE id = 202;
UPDATE locations SET name_ne = 'महोत्तरी' WHERE id = 203;
UPDATE locations SET name_ne = 'पर्सा' WHERE id = 204;
UPDATE locations SET name_ne = 'रौतहट' WHERE id = 205;
UPDATE locations SET name_ne = 'सप्तरी' WHERE id = 206;
UPDATE locations SET name_ne = 'सर्लाही' WHERE id = 207;
UPDATE locations SET name_ne = 'सिराहा' WHERE id = 208;
UPDATE locations SET name_ne = 'काठमाडौं' WHERE id = 301;
UPDATE locations SET name_ne = 'ललितपुर' WHERE id = 302;
UPDATE locations SET name_ne = 'भक्तपुर' WHERE id = 303;
UPDATE locations SET name_ne = 'चितवन' WHERE id = 304;
UPDATE locations SET name_ne = 'मकवानपुर' WHERE id = 305;
UPDATE locations SET name_ne = 'धादिङ' WHERE id = 306;
UPDATE locations SET name_ne = 'नुवाकोट' WHERE id = 307;
UPDATE locations SET name_ne = 'रसुवा' WHERE id = 308;
UPDATE locations SET name_ne = 'सिन्धुली' WHERE id = 309;
UPDATE locations SET name_ne = 'रामेछाप' WHERE id = 310;
UPDATE locations SET name_ne = 'दोलखा' WHERE id = 311;
UPDATE locations SET name_ne = 'सिन्धुपाल्चोक' WHERE id = 312;
UPDATE locations SET name_ne = 'काभ्रेपलाञ्चोक' WHERE id = 313;
UPDATE locations SET name_ne = 'गोरखा' WHERE id = 401;
UPDATE locations SET name_ne = 'लमजुङ' WHERE id = 402;
UPDATE locations SET name_ne = 'कास्की' WHERE id = 403;
UPDATE locations SET name_ne = 'मनाङ' WHERE id = 404;
UPDATE locations SET name_ne = 'मुस्ताङ' WHERE id = 405;
UPDATE locations SET name_ne = 'नवलपुर' WHERE id = 406;
UPDATE locations SET name_ne = 'स्याङजा' WHERE id = 407;
UPDATE locations SET name_ne = 'तनहुँ' WHERE id = 408;
UPDATE locations SET name_ne = 'पर्वत' WHERE id = 409;
UPDATE locations SET name_ne = 'बागलुङ' WHERE id = 410;
UPDATE locations SET name_ne = 'म्याग्दी' WHERE id = 411;
UPDATE locations SET name_ne = 'गुल्मी' WHERE id = 501;
UPDATE locations SET name_ne = 'पाल्पा' WHERE id = 502;
UPDATE locations SET name_ne = 'रुपन्देही' WHERE id = 503;
UPDATE locations SET name_ne = 'कपिलवस्तु' WHERE id = 504;
UPDATE locations SET name_ne = 'अर्घाखाँची' WHERE id = 505;
UPDATE locations SET name_ne = 'प्युठान' WHERE id = 506;
UPDATE locations SET name_ne = 'रोल्पा' WHERE id = 507;
UPDATE locations SET name_ne = 'रुकुम (पूर्वी)' WHERE id = 508;
UPDATE locations SET name_ne = 'बाँके' WHERE id = 509;
UPDATE locations SET name_ne = 'बर्दिया' WHERE id = 510;
UPDATE locations SET name_ne = 'दाङ' WHERE id = 511;
UPDATE locations SET name_ne = 'नवलपरासी (बर्दघाट सुस्ता पश्चिम)' WHERE id = 512;
UPDATE locations SET name_ne = 'रुकुम (पश्चिमी)' WHERE id = 601;
UPDATE locations SET name_ne = 'सल्यान' WHERE id = 602;
UPDATE locations SET name_ne = 'डोल्पा' WHERE id = 603;
UPDATE locations SET name_ne = 'हुम्ला' WHERE id = 604;
UPDATE locations SET name_ne = 'जुम्ला' WHERE id = 605;
UPDATE locations SET name_ne = 'कालिकोट' WHERE id = 606;
UPDATE locations SET name_ne = 'मुगु' WHERE id = 607;
UPDATE locations SET name_ne = 'सुर्खेत' WHERE id = 608;
UPDATE locations SET name_ne = 'दैलेख' WHERE id = 609;
UPDATE locations SET name_ne = 'जाजरकोट' WHERE id = 610;
UPDATE locations SET name_ne = 'कैलाली' WHERE id = 701;
UPDATE locations SET name_ne = 'कञ्चनपुर' WHERE id = 702;
UPDATE locations SET name_ne = 'डडेलधुरा' WHERE id = 703;
UPDATE locations SET name_ne = 'बैतडी' WHERE id = 704;
UPDATE locations SET name_ne = 'डोटी' WHERE id = 705;
UPDATE locations SET name_ne = 'अछाम' WHERE id = 706;
UPDATE locations SET name_ne = 'बझाङ' WHERE id = 707;
UPDATE locations SET name_ne = 'बाजुरा' WHERE id = 708;
UPDATE locations SET name_ne = 'दार्चुला' WHERE id = 709;
UPDATE locations SET name_ne = 'Bhojpur नगरपालिका' WHERE id = 10101;
UPDATE locations SET name_ne = 'Shadananda नगरपालिका' WHERE id = 10102;
UPDATE locations SET name_ne = 'Hatuwagadhi Rural नगरपालिका' WHERE id = 10103;
UPDATE locations SET name_ne = 'Ramprasad Rai Rural नगरपालिका' WHERE id = 10104;
UPDATE locations SET name_ne = 'Aamchowk Rural नगरपालिका' WHERE id = 10105;
UPDATE locations SET name_ne = 'Tyamke Maiyum Rural नगरपालिका' WHERE id = 10106;
UPDATE locations SET name_ne = 'Pauwadungma Rural नगरपालिका' WHERE id = 10107;
UPDATE locations SET name_ne = 'Salpasilichho Rural नगरपालिका' WHERE id = 10108;
UPDATE locations SET name_ne = 'Arun Rural नगरपालिका' WHERE id = 10109;
UPDATE locations SET name_ne = 'Dhankuta नगरपालिका' WHERE id = 10201;
UPDATE locations SET name_ne = 'Mahalaxmi नगरपालिका' WHERE id = 10202;
UPDATE locations SET name_ne = 'Pakhribas नगरपालिका' WHERE id = 10203;
UPDATE locations SET name_ne = 'Sangurigadhi Rural नगरपालिका' WHERE id = 10204;
UPDATE locations SET name_ne = 'Chaubise Rural नगरपालिका' WHERE id = 10205;
UPDATE locations SET name_ne = 'Shahidbhumi Rural नगरपालिका' WHERE id = 10206;
UPDATE locations SET name_ne = 'Chhathar Jorpati Rural नगरपालिका' WHERE id = 10207;
UPDATE locations SET name_ne = 'Ilam नगरपालिका' WHERE id = 10301;
UPDATE locations SET name_ne = 'Deumai नगरपालिका' WHERE id = 10302;
UPDATE locations SET name_ne = 'Mai नगरपालिका' WHERE id = 10303;
UPDATE locations SET name_ne = 'Suryodaya नगरपालिका' WHERE id = 10304;
UPDATE locations SET name_ne = 'Phakphokthum Rural नगरपालिका' WHERE id = 10305;
UPDATE locations SET name_ne = 'Mangsebung Rural नगरपालिका' WHERE id = 10306;
UPDATE locations SET name_ne = 'Rong Rural नगरपालिका' WHERE id = 10307;
UPDATE locations SET name_ne = 'Sandakpur Rural नगरपालिका' WHERE id = 10308;
UPDATE locations SET name_ne = 'Chulachuli Rural नगरपालिका' WHERE id = 10309;
UPDATE locations SET name_ne = 'Maijogmai Rural नगरपालिका' WHERE id = 10310;
UPDATE locations SET name_ne = 'Bhadrapur नगरपालिका' WHERE id = 10401;
UPDATE locations SET name_ne = 'मेचीनगर नगरपालिका' WHERE id = 10402;
UPDATE locations SET name_ne = 'दमक नगरपालिका' WHERE id = 10403;
UPDATE locations SET name_ne = 'Arjundhara नगरपालिका' WHERE id = 10404;
UPDATE locations SET name_ne = 'Gauradaha नगरपालिका' WHERE id = 10405;
UPDATE locations SET name_ne = 'Kankai नगरपालिका' WHERE id = 10406;
UPDATE locations SET name_ne = 'Shivasatakshi नगरपालिका' WHERE id = 10407;
UPDATE locations SET name_ne = 'Kamal Rural नगरपालिका' WHERE id = 10408;
UPDATE locations SET name_ne = 'Gauriganj Rural नगरपालिका' WHERE id = 10409;
UPDATE locations SET name_ne = 'Haldibari Rural नगरपालिका' WHERE id = 10410;
UPDATE locations SET name_ne = 'Jhapa Rural नगरपालिका' WHERE id = 10411;
UPDATE locations SET name_ne = 'Barhadashi Rural नगरपालिका' WHERE id = 10412;
UPDATE locations SET name_ne = 'Buddhashanti Rural नगरपालिका' WHERE id = 10413;
UPDATE locations SET name_ne = 'Kachankawal Rural नगरपालिका' WHERE id = 10414;
UPDATE locations SET name_ne = 'विर्तामोड नगरपालिका' WHERE id = 10415;
UPDATE locations SET name_ne = 'Diktel Rupakot Majhuwagadhi नगरपालिका' WHERE id = 10501;
UPDATE locations SET name_ne = 'Halesi Tuwachung नगरपालिका' WHERE id = 10502;
UPDATE locations SET name_ne = 'Khotehang Rural नगरपालिका' WHERE id = 10503;
UPDATE locations SET name_ne = 'Diprung Rural नगरपालिका' WHERE id = 10504;
UPDATE locations SET name_ne = 'Aiselukharka Rural नगरपालिका' WHERE id = 10505;
UPDATE locations SET name_ne = 'Jantedhunga Rural नगरपालिका' WHERE id = 10506;
UPDATE locations SET name_ne = 'Kepilasgadhi Rural नगरपालिका' WHERE id = 10507;
UPDATE locations SET name_ne = 'Barahapokhari Rural नगरपालिका' WHERE id = 10508;
UPDATE locations SET name_ne = 'Rawabesi Rural नगरपालिका' WHERE id = 10509;
UPDATE locations SET name_ne = 'Sakela Rural नगरपालिका' WHERE id = 10510;
UPDATE locations SET name_ne = 'विराटनगर महानगरपालिका' WHERE id = 10601;
UPDATE locations SET name_ne = 'Sundarharaicha नगरपालिका' WHERE id = 10602;
UPDATE locations SET name_ne = 'Belbari नगरपालिका' WHERE id = 10603;
UPDATE locations SET name_ne = 'Pathari Sanischare नगरपालिका' WHERE id = 10604;
UPDATE locations SET name_ne = 'Urlabari नगरपालिका' WHERE id = 10605;
UPDATE locations SET name_ne = 'Rangeli नगरपालिका' WHERE id = 10606;
UPDATE locations SET name_ne = 'Letang नगरपालिका' WHERE id = 10607;
UPDATE locations SET name_ne = 'Sunbarshi नगरपालिका' WHERE id = 10608;
UPDATE locations SET name_ne = 'Budhiganga Rural नगरपालिका' WHERE id = 10609;
UPDATE locations SET name_ne = 'Gramthan Rural नगरपालिका' WHERE id = 10610;
UPDATE locations SET name_ne = 'Jahada Rural नगरपालिका' WHERE id = 10611;
UPDATE locations SET name_ne = 'Kanepokhari Rural नगरपालिका' WHERE id = 10612;
UPDATE locations SET name_ne = 'Katahari Rural नगरपालिका' WHERE id = 10613;
UPDATE locations SET name_ne = 'Kerabari Rural नगरपालिका' WHERE id = 10614;
UPDATE locations SET name_ne = 'Miklajung Rural नगरपालिका' WHERE id = 10615;
UPDATE locations SET name_ne = 'Dhanpalthan Rural नगरपालिका' WHERE id = 10616;
UPDATE locations SET name_ne = 'Ratuwamai नगरपालिका' WHERE id = 10617;
UPDATE locations SET name_ne = 'Siddhicharan नगरपालिका' WHERE id = 10701;
UPDATE locations SET name_ne = 'Champadevi Rural नगरपालिका' WHERE id = 10702;
UPDATE locations SET name_ne = 'Chisankhugadhi Rural नगरपालिका' WHERE id = 10703;
UPDATE locations SET name_ne = 'Khijidemba Rural नगरपालिका' WHERE id = 10704;
UPDATE locations SET name_ne = 'Likhu Rural नगरपालिका' WHERE id = 10705;
UPDATE locations SET name_ne = 'Manebhanjyang Rural नगरपालिका' WHERE id = 10706;
UPDATE locations SET name_ne = 'Molung Rural नगरपालिका' WHERE id = 10707;
UPDATE locations SET name_ne = 'Phidim नगरपालिका' WHERE id = 10801;
UPDATE locations SET name_ne = 'Hilihang Rural नगरपालिका' WHERE id = 10802;
UPDATE locations SET name_ne = 'Kummayak Rural नगरपालिका' WHERE id = 10803;
UPDATE locations SET name_ne = 'Miklajung Rural नगरपालिका' WHERE id = 10804;
UPDATE locations SET name_ne = 'Phalelung Rural नगरपालिका' WHERE id = 10805;
UPDATE locations SET name_ne = 'Phalgunanda Rural नगरपालिका' WHERE id = 10806;
UPDATE locations SET name_ne = 'Tumbewa Rural नगरपालिका' WHERE id = 10807;
UPDATE locations SET name_ne = 'Yangwarak Rural नगरपालिका' WHERE id = 10808;
UPDATE locations SET name_ne = 'Khandbari नगरपालिका' WHERE id = 10901;
UPDATE locations SET name_ne = 'Chainpur नगरपालिका' WHERE id = 10902;
UPDATE locations SET name_ne = 'Dharmadevi नगरपालिका' WHERE id = 10903;
UPDATE locations SET name_ne = 'Madi नगरपालिका' WHERE id = 10904;
UPDATE locations SET name_ne = 'Panchkhapan नगरपालिका' WHERE id = 10905;
UPDATE locations SET name_ne = 'Makalu Rural नगरपालिका' WHERE id = 10906;
UPDATE locations SET name_ne = 'Silichong Rural नगरपालिका' WHERE id = 10907;
UPDATE locations SET name_ne = 'Sabhapokhari Rural नगरपालिका' WHERE id = 10908;
UPDATE locations SET name_ne = 'Chichila Rural नगरपालिका' WHERE id = 10909;
UPDATE locations SET name_ne = 'Bhotkhola Rural नगरपालिका' WHERE id = 10910;
UPDATE locations SET name_ne = 'Solududhakunda नगरपालिका' WHERE id = 11001;
UPDATE locations SET name_ne = 'Khumbu Pasanglhamu Rural नगरपालिका' WHERE id = 11002;
UPDATE locations SET name_ne = 'Mahakulung Rural नगरपालिका' WHERE id = 11003;
UPDATE locations SET name_ne = 'Necha Salyan Rural नगरपालिका' WHERE id = 11004;
UPDATE locations SET name_ne = 'Sotang Rural नगरपालिका' WHERE id = 11005;
UPDATE locations SET name_ne = 'Likhupike Rural नगरपालिका' WHERE id = 11006;
UPDATE locations SET name_ne = 'Thulung Dudhkoshi Rural नगरपालिका' WHERE id = 11007;
UPDATE locations SET name_ne = 'Mapya Dudhkoshi Rural नगरपालिका' WHERE id = 11008;
UPDATE locations SET name_ne = 'इटहरी उप-महानगरपालिका' WHERE id = 11101;
UPDATE locations SET name_ne = 'धरान उप-महानगरपालिका' WHERE id = 11102;
UPDATE locations SET name_ne = 'इनरुवा नगरपालिका' WHERE id = 11103;
UPDATE locations SET name_ne = 'Duhabi नगरपालिका' WHERE id = 11104;
UPDATE locations SET name_ne = 'Ramdhuni नगरपालिका' WHERE id = 11105;
UPDATE locations SET name_ne = 'Barahachhetra नगरपालिका' WHERE id = 11106;
UPDATE locations SET name_ne = 'Koshi Rural नगरपालिका' WHERE id = 11107;
UPDATE locations SET name_ne = 'Gadhi Rural नगरपालिका' WHERE id = 11108;
UPDATE locations SET name_ne = 'Barjung Rural नगरपालिका' WHERE id = 11109;
UPDATE locations SET name_ne = 'Bhokraha Rural नगरपालिका' WHERE id = 11110;
UPDATE locations SET name_ne = 'Harinagar Rural नगरपालिका' WHERE id = 11111;
UPDATE locations SET name_ne = 'Dewanganj Rural नगरपालिका' WHERE id = 11112;
UPDATE locations SET name_ne = 'Phungling नगरपालिका' WHERE id = 11201;
UPDATE locations SET name_ne = 'Aathrai Triveni Rural नगरपालिका' WHERE id = 11202;
UPDATE locations SET name_ne = 'Sidingwa Rural नगरपालिका' WHERE id = 11203;
UPDATE locations SET name_ne = 'Phaktanglung Rural नगरपालिका' WHERE id = 11204;
UPDATE locations SET name_ne = 'Meringden Rural नगरपालिका' WHERE id = 11205;
UPDATE locations SET name_ne = 'Maiwakhola Rural नगरपालिका' WHERE id = 11206;
UPDATE locations SET name_ne = 'Mikwakhola Rural नगरपालिका' WHERE id = 11207;
UPDATE locations SET name_ne = 'Pathivara Yangwarak Rural नगरपालिका' WHERE id = 11208;
UPDATE locations SET name_ne = 'Sirijangha Rural नगरपालिका' WHERE id = 11209;
UPDATE locations SET name_ne = 'Myanglung नगरपालिका' WHERE id = 11301;
UPDATE locations SET name_ne = 'Laligurans नगरपालिका' WHERE id = 11302;
UPDATE locations SET name_ne = 'Aathrai Rural नगरपालिका' WHERE id = 11303;
UPDATE locations SET name_ne = 'Chhathar Rural नगरपालिका' WHERE id = 11304;
UPDATE locations SET name_ne = 'Phedap Rural नगरपालिका' WHERE id = 11305;
UPDATE locations SET name_ne = 'Menchhayayem Rural नगरपालिका' WHERE id = 11306;
UPDATE locations SET name_ne = 'Triyuga नगरपालिका' WHERE id = 11401;
UPDATE locations SET name_ne = 'Katari नगरपालिका' WHERE id = 11402;
UPDATE locations SET name_ne = 'Chaudandigadhi नगरपालिका' WHERE id = 11403;
UPDATE locations SET name_ne = 'Belaka नगरपालिका' WHERE id = 11404;
UPDATE locations SET name_ne = 'Udayapurgadhi Rural नगरपालिका' WHERE id = 11405;
UPDATE locations SET name_ne = 'Rautamai Rural नगरपालिका' WHERE id = 11406;
UPDATE locations SET name_ne = 'Tapli Rural नगरपालिका' WHERE id = 11407;
UPDATE locations SET name_ne = 'Limchungbung Rural नगरपालिका' WHERE id = 11408;
UPDATE locations SET name_ne = 'कलैया उप-महानगरपालिका' WHERE id = 20101;
UPDATE locations SET name_ne = 'Jeetpur Simara Sub- महानगरपालिका' WHERE id = 20102;
UPDATE locations SET name_ne = 'Nijgadh नगरपालिका' WHERE id = 20103;
UPDATE locations SET name_ne = 'Kolhabi नगरपालिका' WHERE id = 20104;
UPDATE locations SET name_ne = 'Mahagadhimai नगरपालिका' WHERE id = 20105;
UPDATE locations SET name_ne = 'Simraungadh नगरपालिका' WHERE id = 20106;
UPDATE locations SET name_ne = 'Pachrauta नगरपालिका' WHERE id = 20107;
UPDATE locations SET name_ne = 'Pheta Rural नगरपालिका' WHERE id = 20108;
UPDATE locations SET name_ne = 'Bishrampur Rural नगरपालिका' WHERE id = 20109;
UPDATE locations SET name_ne = 'Prasauni Rural नगरपालिका' WHERE id = 20110;
UPDATE locations SET name_ne = 'Suvarna Rural नगरपालिका' WHERE id = 20111;
UPDATE locations SET name_ne = 'Baragadhi Rural नगरपालिका' WHERE id = 20112;
UPDATE locations SET name_ne = 'Parwanipur Rural नगरपालिका' WHERE id = 20113;
UPDATE locations SET name_ne = 'Adarsh Kotwal Rural नगरपालिका' WHERE id = 20114;
UPDATE locations SET name_ne = 'Karaiyamai Rural नगरपालिका' WHERE id = 20115;
UPDATE locations SET name_ne = 'Devtal Rural नगरपालिका' WHERE id = 20116;
UPDATE locations SET name_ne = 'जनकपुरधाम उप-महानगरपालिका' WHERE id = 20201;
UPDATE locations SET name_ne = 'Chhireshwarnath नगरपालिका' WHERE id = 20202;
UPDATE locations SET name_ne = 'Ganeshman Charnath नगरपालिका' WHERE id = 20203;
UPDATE locations SET name_ne = 'Dhanushadham नगरपालिका' WHERE id = 20204;
UPDATE locations SET name_ne = 'Mithila नगरपालिका' WHERE id = 20205;
UPDATE locations SET name_ne = 'Shahidnagar नगरपालिका' WHERE id = 20206;
UPDATE locations SET name_ne = 'Sabaila नगरपालिका' WHERE id = 20207;
UPDATE locations SET name_ne = 'Nagarain नगरपालिका' WHERE id = 20208;
UPDATE locations SET name_ne = 'Kamala नगरपालिका' WHERE id = 20209;
UPDATE locations SET name_ne = 'Bateshwar Rural नगरपालिका' WHERE id = 20210;
UPDATE locations SET name_ne = 'Mukhiyapatti Musaharmiya Rural नगरपालिका' WHERE id = 20211;
UPDATE locations SET name_ne = 'Aaurahi Rural नगरपालिका' WHERE id = 20212;
UPDATE locations SET name_ne = 'Janak Nandini Rural नगरपालिका' WHERE id = 20213;
UPDATE locations SET name_ne = 'Laxminiya Rural नगरपालिका' WHERE id = 20214;
UPDATE locations SET name_ne = 'Hansapur नगरपालिका' WHERE id = 20215;
UPDATE locations SET name_ne = 'Dhanauji Rural नगरपालिका' WHERE id = 20216;
UPDATE locations SET name_ne = 'Mithila Bihari नगरपालिका' WHERE id = 20217;
UPDATE locations SET name_ne = 'Bideha नगरपालिका' WHERE id = 20218;
UPDATE locations SET name_ne = 'Jaleshwar नगरपालिका' WHERE id = 20301;
UPDATE locations SET name_ne = 'Bardibas नगरपालिका' WHERE id = 20302;
UPDATE locations SET name_ne = 'Gaushala नगरपालिका' WHERE id = 20303;
UPDATE locations SET name_ne = 'Loharpatti नगरपालिका' WHERE id = 20304;
UPDATE locations SET name_ne = 'Ramgopalpur नगरपालिका' WHERE id = 20305;
UPDATE locations SET name_ne = 'Manara Shiswa नगरपालिका' WHERE id = 20306;
UPDATE locations SET name_ne = 'Matihani नगरपालिका' WHERE id = 20307;
UPDATE locations SET name_ne = 'Balwa नगरपालिका' WHERE id = 20308;
UPDATE locations SET name_ne = 'Bhangaha नगरपालिका' WHERE id = 20309;
UPDATE locations SET name_ne = 'Aurahi Rural नगरपालिका' WHERE id = 20310;
UPDATE locations SET name_ne = 'Ekdara Rural नगरपालिका' WHERE id = 20311;
UPDATE locations SET name_ne = 'Mahottari Rural नगरपालिका' WHERE id = 20312;
UPDATE locations SET name_ne = 'Pipra Rural नगरपालिका' WHERE id = 20313;
UPDATE locations SET name_ne = 'Samsi Rural नगरपालिका' WHERE id = 20314;
UPDATE locations SET name_ne = 'Sonama Rural नगरपालिका' WHERE id = 20315;
UPDATE locations SET name_ne = 'वीरगञ्ज महानगरपालिका' WHERE id = 20401;
UPDATE locations SET name_ne = 'Bahudaramai नगरपालिका' WHERE id = 20402;
UPDATE locations SET name_ne = 'Parsagadhi नगरपालिका' WHERE id = 20403;
UPDATE locations SET name_ne = 'Pokhariya नगरपालिका' WHERE id = 20404;
UPDATE locations SET name_ne = 'Bindabasini Rural नगरपालिका' WHERE id = 20405;
UPDATE locations SET name_ne = 'Dhobini Rural नगरपालिका' WHERE id = 20406;
UPDATE locations SET name_ne = 'Chhipaharmai Rural नगरपालिका' WHERE id = 20407;
UPDATE locations SET name_ne = 'Jagarnathpur Rural नगरपालिका' WHERE id = 20408;
UPDATE locations SET name_ne = 'Jirabhawani Rural नगरपालिका' WHERE id = 20409;
UPDATE locations SET name_ne = 'Kalikamai Rural नगरपालिका' WHERE id = 20410;
UPDATE locations SET name_ne = 'Paterwa Sugauli Rural नगरपालिका' WHERE id = 20411;
UPDATE locations SET name_ne = 'Sakhuwa Prasauni Rural नगरपालिका' WHERE id = 20412;
UPDATE locations SET name_ne = 'Thori Rural नगरपालिका' WHERE id = 20413;
UPDATE locations SET name_ne = 'Pakaha Mainpur Rural नगरपालिका' WHERE id = 20414;
UPDATE locations SET name_ne = 'Chandrapur नगरपालिका' WHERE id = 20501;
UPDATE locations SET name_ne = 'Garuda नगरपालिका' WHERE id = 20502;
UPDATE locations SET name_ne = 'गौर नगरपालिका' WHERE id = 20503;
UPDATE locations SET name_ne = 'Baudhimai नगरपालिका' WHERE id = 20504;
UPDATE locations SET name_ne = 'Brindaban नगरपालिका' WHERE id = 20505;
UPDATE locations SET name_ne = 'Dewahi Gonahi नगरपालिका' WHERE id = 20506;
UPDATE locations SET name_ne = 'Gadhimai नगरपालिका' WHERE id = 20507;
UPDATE locations SET name_ne = 'Gujara नगरपालिका' WHERE id = 20508;
UPDATE locations SET name_ne = 'Ishnath नगरपालिका' WHERE id = 20509;
UPDATE locations SET name_ne = 'Katahariya नगरपालिका' WHERE id = 20510;
UPDATE locations SET name_ne = 'Madhav Narayan नगरपालिका' WHERE id = 20511;
UPDATE locations SET name_ne = 'Maulapur नगरपालिका' WHERE id = 20512;
UPDATE locations SET name_ne = 'Paroha नगरपालिका' WHERE id = 20513;
UPDATE locations SET name_ne = 'Phatuwa Bijayapur नगरपालिका' WHERE id = 20514;
UPDATE locations SET name_ne = 'Rajdevi नगरपालिका' WHERE id = 20515;
UPDATE locations SET name_ne = 'Rajpur नगरपालिका' WHERE id = 20516;
UPDATE locations SET name_ne = 'Durga Bhagwati Rural नगरपालिका' WHERE id = 20517;
UPDATE locations SET name_ne = 'Yamunamai Rural नगरपालिका' WHERE id = 20518;
UPDATE locations SET name_ne = 'राजविराज नगरपालिका' WHERE id = 20601;
UPDATE locations SET name_ne = 'Bodebarsain नगरपालिका' WHERE id = 20602;
UPDATE locations SET name_ne = 'Dakneshwari नगरपालिका' WHERE id = 20603;
UPDATE locations SET name_ne = 'Hanumannagar Kankalini नगरपालिका' WHERE id = 20604;
UPDATE locations SET name_ne = 'Kanchanrup नगरपालिका' WHERE id = 20605;
UPDATE locations SET name_ne = 'Khadak नगरपालिका' WHERE id = 20606;
UPDATE locations SET name_ne = 'Shambhunath नगरपालिका' WHERE id = 20607;
UPDATE locations SET name_ne = 'Saptakoshi नगरपालिका' WHERE id = 20608;
UPDATE locations SET name_ne = 'Surunga नगरपालिका' WHERE id = 20609;
UPDATE locations SET name_ne = 'Agnisair Krishna Savaran Rural नगरपालिका' WHERE id = 20610;
UPDATE locations SET name_ne = 'Bishnupur Rural नगरपालिका' WHERE id = 20611;
UPDATE locations SET name_ne = 'Chhinnamasta Rural नगरपालिका' WHERE id = 20612;
UPDATE locations SET name_ne = 'Mahadeva Rural नगरपालिका' WHERE id = 20613;
UPDATE locations SET name_ne = 'Rajgadh Rural नगरपालिका' WHERE id = 20614;
UPDATE locations SET name_ne = 'Rupani Rural नगरपालिका' WHERE id = 20615;
UPDATE locations SET name_ne = 'Tirahut Rural नगरपालिका' WHERE id = 20616;
UPDATE locations SET name_ne = 'Tilathi Koiladi Rural नगरपालिका' WHERE id = 20617;
UPDATE locations SET name_ne = 'Balan Bihul Rural नगरपालिका' WHERE id = 20618;
UPDATE locations SET name_ne = 'Bagmati नगरपालिका' WHERE id = 20701;
UPDATE locations SET name_ne = 'Balara नगरपालिका' WHERE id = 20702;
UPDATE locations SET name_ne = 'Barahathwa नगरपालिका' WHERE id = 20703;
UPDATE locations SET name_ne = 'Godaita नगरपालिका' WHERE id = 20704;
UPDATE locations SET name_ne = 'Haripur नगरपालिका' WHERE id = 20705;
UPDATE locations SET name_ne = 'Haripurwa नगरपालिका' WHERE id = 20706;
UPDATE locations SET name_ne = 'Hariwan नगरपालिका' WHERE id = 20707;
UPDATE locations SET name_ne = 'Ishworpur नगरपालिका' WHERE id = 20708;
UPDATE locations SET name_ne = 'Kabilasi नगरपालिका' WHERE id = 20709;
UPDATE locations SET name_ne = 'Lalbandi नगरपालिका' WHERE id = 20710;
UPDATE locations SET name_ne = 'Malangwa नगरपालिका' WHERE id = 20711;
UPDATE locations SET name_ne = 'Basbariya Rural नगरपालिका' WHERE id = 20712;
UPDATE locations SET name_ne = 'Bishnu Rural नगरपालिका' WHERE id = 20713;
UPDATE locations SET name_ne = 'Brahmapuri Rural नगरपालिका' WHERE id = 20714;
UPDATE locations SET name_ne = 'Chakraghatta Rural नगरपालिका' WHERE id = 20715;
UPDATE locations SET name_ne = 'Chandranagar Rural नगरपालिका' WHERE id = 20716;
UPDATE locations SET name_ne = 'Dhankaul Rural नगरपालिका' WHERE id = 20717;
UPDATE locations SET name_ne = 'Kaudena Rural नगरपालिका' WHERE id = 20718;
UPDATE locations SET name_ne = 'Parsa Rural नगरपालिका' WHERE id = 20719;
UPDATE locations SET name_ne = 'Ramnagar Rural नगरपालिका' WHERE id = 20720;
UPDATE locations SET name_ne = 'लहान नगरपालिका' WHERE id = 20801;
UPDATE locations SET name_ne = 'Dhangadhimai नगरपालिका' WHERE id = 20802;
UPDATE locations SET name_ne = 'Siraha नगरपालिका' WHERE id = 20803;
UPDATE locations SET name_ne = 'Golbazar नगरपालिका' WHERE id = 20804;
UPDATE locations SET name_ne = 'Mirchaiya नगरपालिका' WHERE id = 20805;
UPDATE locations SET name_ne = 'Kalyanpur नगरपालिका' WHERE id = 20806;
UPDATE locations SET name_ne = 'Karjanha नगरपालिका' WHERE id = 20807;
UPDATE locations SET name_ne = 'Sukhipur नगरपालिका' WHERE id = 20808;
UPDATE locations SET name_ne = 'Bhagwanpur Rural नगरपालिका' WHERE id = 20809;
UPDATE locations SET name_ne = 'Aurahi Rural नगरपालिका' WHERE id = 20810;
UPDATE locations SET name_ne = 'Bishnupur Rural नगरपालिका' WHERE id = 20811;
UPDATE locations SET name_ne = 'Bariyarpatti Rural नगरपालिका' WHERE id = 20812;
UPDATE locations SET name_ne = 'Laxmipur Patari Rural नगरपालिका' WHERE id = 20813;
UPDATE locations SET name_ne = 'Naraha Rural नगरपालिका' WHERE id = 20814;
UPDATE locations SET name_ne = 'Sakhuwa Nankarkatti Rural नगरपालिका' WHERE id = 20815;
UPDATE locations SET name_ne = 'Arnama Rural नगरपालिका' WHERE id = 20816;
UPDATE locations SET name_ne = 'Navarajpur Rural नगरपालिका' WHERE id = 20817;
UPDATE locations SET name_ne = 'काठमाडौं महानगरपालिका' WHERE id = 30101;
UPDATE locations SET name_ne = 'बूढानीलकण्ठ नगरपालिका' WHERE id = 30102;
UPDATE locations SET name_ne = 'चन्द्रागिरी नगरपालिका' WHERE id = 30103;
UPDATE locations SET name_ne = 'Dakshinkali नगरपालिका' WHERE id = 30104;
UPDATE locations SET name_ne = 'Gokarneshwor नगरपालिका' WHERE id = 30105;
UPDATE locations SET name_ne = 'Kageshwori Manohara नगरपालिका' WHERE id = 30106;
UPDATE locations SET name_ne = 'कीर्तिपुर नगरपालिका' WHERE id = 30107;
UPDATE locations SET name_ne = 'Nagarjun नगरपालिका' WHERE id = 30108;
UPDATE locations SET name_ne = 'Shankharapur नगरपालिका' WHERE id = 30109;
UPDATE locations SET name_ne = 'Tarakeshwar नगरपालिका' WHERE id = 30110;
UPDATE locations SET name_ne = 'टोखा नगरपालिका' WHERE id = 30111;
UPDATE locations SET name_ne = 'ललितपुर महानगरपालिका' WHERE id = 30201;
UPDATE locations SET name_ne = 'Godawari नगरपालिका' WHERE id = 30202;
UPDATE locations SET name_ne = 'Mahalaxmi नगरपालिका' WHERE id = 30203;
UPDATE locations SET name_ne = 'Konjyosom Rural नगरपालिका' WHERE id = 30204;
UPDATE locations SET name_ne = 'Bagmati Rural नगरपालिका' WHERE id = 30205;
UPDATE locations SET name_ne = 'Mahankal Rural नगरपालिका' WHERE id = 30206;
UPDATE locations SET name_ne = 'भक्तपुर नगरपालिका' WHERE id = 30301;
UPDATE locations SET name_ne = 'Changunarayan नगरपालिका' WHERE id = 30302;
UPDATE locations SET name_ne = 'मध्यपुर थिमी नगरपालिका' WHERE id = 30303;
UPDATE locations SET name_ne = 'Suryabinayak नगरपालिका' WHERE id = 30304;
UPDATE locations SET name_ne = 'भरतपुर महानगरपालिका' WHERE id = 30401;
UPDATE locations SET name_ne = 'Kalika नगरपालिका' WHERE id = 30402;
UPDATE locations SET name_ne = 'Khairahani नगरपालिका' WHERE id = 30403;
UPDATE locations SET name_ne = 'Madi नगरपालिका' WHERE id = 30404;
UPDATE locations SET name_ne = 'Ratnanagar नगरपालिका' WHERE id = 30405;
UPDATE locations SET name_ne = 'Rapti नगरपालिका' WHERE id = 30406;
UPDATE locations SET name_ne = 'Ichchhakamana Rural नगरपालिका' WHERE id = 30407;
UPDATE locations SET name_ne = 'हेटौंडा उप-महानगरपालिका' WHERE id = 30501;
UPDATE locations SET name_ne = 'Thaha नगरपालिका' WHERE id = 30502;
UPDATE locations SET name_ne = 'Bhimphedi Rural नगरपालिका' WHERE id = 30503;
UPDATE locations SET name_ne = 'Makawanpurgadhi Rural नगरपालिका' WHERE id = 30504;
UPDATE locations SET name_ne = 'Manahari Rural नगरपालिका' WHERE id = 30505;
UPDATE locations SET name_ne = 'Raksirang Rural नगरपालिका' WHERE id = 30506;
UPDATE locations SET name_ne = 'Bakaiya Rural नगरपालिका' WHERE id = 30507;
UPDATE locations SET name_ne = 'Bagmati Rural नगरपालिका' WHERE id = 30508;
UPDATE locations SET name_ne = 'Kailash Rural नगरपालिका' WHERE id = 30509;
UPDATE locations SET name_ne = 'Indrasarowar Rural नगरपालिका' WHERE id = 30510;
UPDATE locations SET name_ne = 'Dhading Besi नगरपालिका' WHERE id = 30601;
UPDATE locations SET name_ne = 'Nilkantha नगरपालिका' WHERE id = 30602;
UPDATE locations SET name_ne = 'Khaniyabas Rural नगरपालिका' WHERE id = 30603;
UPDATE locations SET name_ne = 'Gajuri Rural नगरपालिका' WHERE id = 30604;
UPDATE locations SET name_ne = 'Galchi Rural नगरपालिका' WHERE id = 30605;
UPDATE locations SET name_ne = 'Gangajamuna Rural नगरपालिका' WHERE id = 30606;
UPDATE locations SET name_ne = 'Jwalamukhi Rural नगरपालिका' WHERE id = 30607;
UPDATE locations SET name_ne = 'Netrawati Dabjong Rural नगरपालिका' WHERE id = 30608;
UPDATE locations SET name_ne = 'Benighat Rorang Rural नगरपालिका' WHERE id = 30609;
UPDATE locations SET name_ne = 'Ruby Valley Rural नगरपालिका' WHERE id = 30610;
UPDATE locations SET name_ne = 'Siddhalek Rural नगरपालिका' WHERE id = 30611;
UPDATE locations SET name_ne = 'Thakre Rural नगरपालिका' WHERE id = 30612;
UPDATE locations SET name_ne = 'Tripura Sundari Rural नगरपालिका' WHERE id = 30613;
UPDATE locations SET name_ne = 'Bidur नगरपालिका' WHERE id = 30701;
UPDATE locations SET name_ne = 'Belkotgadhi नगरपालिका' WHERE id = 30702;
UPDATE locations SET name_ne = 'Kakani Rural नगरपालिका' WHERE id = 30703;
UPDATE locations SET name_ne = 'Kispang Rural नगरपालिका' WHERE id = 30704;
UPDATE locations SET name_ne = 'Likhu Rural नगरपालिका' WHERE id = 30705;
UPDATE locations SET name_ne = 'Myagang Rural नगरपालिका' WHERE id = 30706;
UPDATE locations SET name_ne = 'Panchakanya Rural नगरपालिका' WHERE id = 30707;
UPDATE locations SET name_ne = 'Shivapuri Rural नगरपालिका' WHERE id = 30708;
UPDATE locations SET name_ne = 'Dupcheshwor Rural नगरपालिका' WHERE id = 30709;
UPDATE locations SET name_ne = 'Suryagadhi Rural नगरपालिका' WHERE id = 30710;
UPDATE locations SET name_ne = 'Tadi Rural नगरपालिका' WHERE id = 30711;
UPDATE locations SET name_ne = 'Tarkeshwar Rural नगरपालिका' WHERE id = 30712;
UPDATE locations SET name_ne = 'Gosaikunda Rural नगरपालिका' WHERE id = 30801;
UPDATE locations SET name_ne = 'Kalika Rural नगरपालिका' WHERE id = 30802;
UPDATE locations SET name_ne = 'Naukunda Rural नगरपालिका' WHERE id = 30803;
UPDATE locations SET name_ne = 'Parbatikunda Rural नगरपालिका' WHERE id = 30804;
UPDATE locations SET name_ne = 'Uttargaya Rural नगरपालिका' WHERE id = 30805;
UPDATE locations SET name_ne = 'Kamalamai नगरपालिका' WHERE id = 30901;
UPDATE locations SET name_ne = 'Dudhouli नगरपालिका' WHERE id = 30902;
UPDATE locations SET name_ne = 'Golanjor Rural नगरपालिका' WHERE id = 30903;
UPDATE locations SET name_ne = 'Ghyanglekh Rural नगरपालिका' WHERE id = 30904;
UPDATE locations SET name_ne = 'Hariharpurgadhi Rural नगरपालिका' WHERE id = 30905;
UPDATE locations SET name_ne = 'Marin Rural नगरपालिका' WHERE id = 30906;
UPDATE locations SET name_ne = 'Phikkal Rural नगरपालिका' WHERE id = 30907;
UPDATE locations SET name_ne = 'Sunkoshi Rural नगरपालिका' WHERE id = 30908;
UPDATE locations SET name_ne = 'Tinpatan Rural नगरपालिका' WHERE id = 30909;
UPDATE locations SET name_ne = 'Ramechhap नगरपालिका' WHERE id = 31001;
UPDATE locations SET name_ne = 'Manthali नगरपालिका' WHERE id = 31002;
UPDATE locations SET name_ne = 'Umakunda Rural नगरपालिका' WHERE id = 31003;
UPDATE locations SET name_ne = 'Khandadevi Rural नगरपालिका' WHERE id = 31004;
UPDATE locations SET name_ne = 'Likhu Tamakoshi Rural नगरपालिका' WHERE id = 31005;
UPDATE locations SET name_ne = 'Doramba Rural नगरपालिका' WHERE id = 31006;
UPDATE locations SET name_ne = 'Gokulganga Rural नगरपालिका' WHERE id = 31007;
UPDATE locations SET name_ne = 'Sunapati Rural नगरपालिका' WHERE id = 31008;
UPDATE locations SET name_ne = 'Bhimeshwar नगरपालिका' WHERE id = 31101;
UPDATE locations SET name_ne = 'Jiri नगरपालिका' WHERE id = 31102;
UPDATE locations SET name_ne = 'Baiteshwor Rural नगरपालिका' WHERE id = 31103;
UPDATE locations SET name_ne = 'Bigu Rural नगरपालिका' WHERE id = 31104;
UPDATE locations SET name_ne = 'Gaurishankar Rural नगरपालिका' WHERE id = 31105;
UPDATE locations SET name_ne = 'Kalinchok Rural नगरपालिका' WHERE id = 31106;
UPDATE locations SET name_ne = 'Melung Rural नगरपालिका' WHERE id = 31107;
UPDATE locations SET name_ne = 'Sailung Rural नगरपालिका' WHERE id = 31108;
UPDATE locations SET name_ne = 'Tamakoshi Rural नगरपालिका' WHERE id = 31109;
UPDATE locations SET name_ne = 'Chautara Sangachokgadhi नगरपालिका' WHERE id = 31201;
UPDATE locations SET name_ne = 'Barhabise नगरपालिका' WHERE id = 31202;
UPDATE locations SET name_ne = 'Melamchi नगरपालिका' WHERE id = 31203;
UPDATE locations SET name_ne = 'Balefi Rural नगरपालिका' WHERE id = 31204;
UPDATE locations SET name_ne = 'Bhotekoshi Rural नगरपालिका' WHERE id = 31205;
UPDATE locations SET name_ne = 'Helambu Rural नगरपालिका' WHERE id = 31206;
UPDATE locations SET name_ne = 'Indrawati Rural नगरपालिका' WHERE id = 31207;
UPDATE locations SET name_ne = 'Jugal Rural नगरपालिका' WHERE id = 31208;
UPDATE locations SET name_ne = 'Lisankhu Pakhar Rural नगरपालिका' WHERE id = 31209;
UPDATE locations SET name_ne = 'Panchpokhari Thangpal Rural नगरपालिका' WHERE id = 31210;
UPDATE locations SET name_ne = 'Tripurasundari Rural नगरपालिका' WHERE id = 31212;
UPDATE locations SET name_ne = 'Dhulikhel नगरपालिका' WHERE id = 31301;
UPDATE locations SET name_ne = 'Banepa नगरपालिका' WHERE id = 31302;
UPDATE locations SET name_ne = 'Panauti नगरपालिका' WHERE id = 31303;
UPDATE locations SET name_ne = 'Panchkhal नगरपालिका' WHERE id = 31304;
UPDATE locations SET name_ne = 'Namobuddha नगरपालिका' WHERE id = 31305;
UPDATE locations SET name_ne = 'Mandan Deupur नगरपालिका' WHERE id = 31306;
UPDATE locations SET name_ne = 'Khanikhola Rural नगरपालिका' WHERE id = 31307;
UPDATE locations SET name_ne = 'Chauri Deurali Rural नगरपालिका' WHERE id = 31308;
UPDATE locations SET name_ne = 'Temal Rural नगरपालिका' WHERE id = 31309;
UPDATE locations SET name_ne = 'Bethanchok Rural नगरपालिका' WHERE id = 31310;
UPDATE locations SET name_ne = 'Bhumlu Rural नगरपालिका' WHERE id = 31311;
UPDATE locations SET name_ne = 'Mahabharat Rural नगरपालिका' WHERE id = 31312;
UPDATE locations SET name_ne = 'Roshi Rural नगरपालिका' WHERE id = 31313;
UPDATE locations SET name_ne = 'गोरखा नगरपालिका' WHERE id = 40101;
UPDATE locations SET name_ne = 'Palungtar नगरपालिका' WHERE id = 40102;
UPDATE locations SET name_ne = 'Sulikot Rural नगरपालिका' WHERE id = 40103;
UPDATE locations SET name_ne = 'Siranchok Rural नगरपालिका' WHERE id = 40104;
UPDATE locations SET name_ne = 'Ajirkot Rural नगरपालिका' WHERE id = 40105;
UPDATE locations SET name_ne = 'Tsum Nubri Rural नगरपालिका' WHERE id = 40106;
UPDATE locations SET name_ne = 'Dharche Rural नगरपालिका' WHERE id = 40107;
UPDATE locations SET name_ne = 'Bhimsen Thapa Rural नगरपालिका' WHERE id = 40108;
UPDATE locations SET name_ne = 'Sahid Lakhan Rural नगरपालिका' WHERE id = 40109;
UPDATE locations SET name_ne = 'Aarughat Rural नगरपालिका' WHERE id = 40110;
UPDATE locations SET name_ne = 'Gandaki Rural नगरपालिका' WHERE id = 40111;
UPDATE locations SET name_ne = 'Besisahar नगरपालिका' WHERE id = 40201;
UPDATE locations SET name_ne = 'Madhya Nepal नगरपालिका' WHERE id = 40202;
UPDATE locations SET name_ne = 'Rainas नगरपालिका' WHERE id = 40203;
UPDATE locations SET name_ne = 'Sundarbazar नगरपालिका' WHERE id = 40204;
UPDATE locations SET name_ne = 'Kwholasothar Rural नगरपालिका' WHERE id = 40205;
UPDATE locations SET name_ne = 'Dudhpokhari Rural नगरपालिका' WHERE id = 40206;
UPDATE locations SET name_ne = 'Dordi Rural नगरपालिका' WHERE id = 40207;
UPDATE locations SET name_ne = 'Marsyangdi Rural नगरपालिका' WHERE id = 40208;
UPDATE locations SET name_ne = 'पोखरा महानगरपालिका' WHERE id = 40301;
UPDATE locations SET name_ne = 'Annapurna Rural नगरपालिका' WHERE id = 40302;
UPDATE locations SET name_ne = 'Machhapuchchhre Rural नगरपालिका' WHERE id = 40303;
UPDATE locations SET name_ne = 'Madi Rural नगरपालिका' WHERE id = 40304;
UPDATE locations SET name_ne = 'Rupa Rural नगरपालिका' WHERE id = 40305;
UPDATE locations SET name_ne = 'Chame Rural नगरपालिका' WHERE id = 40401;
UPDATE locations SET name_ne = 'Nason Rural नगरपालिका' WHERE id = 40402;
UPDATE locations SET name_ne = 'Narpa Bhumi Rural नगरपालिका' WHERE id = 40403;
UPDATE locations SET name_ne = 'Manang Ngisyang Rural नगरपालिका' WHERE id = 40404;
UPDATE locations SET name_ne = 'Gharapjhong Rural नगरपालिका' WHERE id = 40501;
UPDATE locations SET name_ne = 'Thasang Rural नगरपालिका' WHERE id = 40502;
UPDATE locations SET name_ne = 'Barhagaun Muktichhetra Rural नगरपालिका' WHERE id = 40503;
UPDATE locations SET name_ne = 'Lomanthang Rural नगरपालिका' WHERE id = 40504;
UPDATE locations SET name_ne = 'Lo-Ghekar Damodarkunda Rural नगरपालिका' WHERE id = 40505;
UPDATE locations SET name_ne = 'Kawasoti नगरपालिका' WHERE id = 40601;
UPDATE locations SET name_ne = 'Gaindakot नगरपालिका' WHERE id = 40602;
UPDATE locations SET name_ne = 'Devchuli नगरपालिका' WHERE id = 40603;
UPDATE locations SET name_ne = 'Madhyabindu नगरपालिका' WHERE id = 40604;
UPDATE locations SET name_ne = 'Baudikali Rural नगरपालिका' WHERE id = 40605;
UPDATE locations SET name_ne = 'Bulingtar Rural नगरपालिका' WHERE id = 40606;
UPDATE locations SET name_ne = 'Binayi Tribeni Rural नगरपालिका' WHERE id = 40607;
UPDATE locations SET name_ne = 'Hupsekot Rural नगरपालिका' WHERE id = 40608;
UPDATE locations SET name_ne = 'Galyang नगरपालिका' WHERE id = 40701;
UPDATE locations SET name_ne = 'Chapakot नगरपालिका' WHERE id = 40702;
UPDATE locations SET name_ne = 'Putalibazar नगरपालिका' WHERE id = 40703;
UPDATE locations SET name_ne = 'Bhirkot नगरपालिका' WHERE id = 40704;
UPDATE locations SET name_ne = 'Waling नगरपालिका' WHERE id = 40705;
UPDATE locations SET name_ne = 'Arjun Chaupari Rural नगरपालिका' WHERE id = 40706;
UPDATE locations SET name_ne = 'Aandhikhola Rural नगरपालिका' WHERE id = 40707;
UPDATE locations SET name_ne = 'Kaligandaki Rural नगरपालिका' WHERE id = 40708;
UPDATE locations SET name_ne = 'Phedikhola Rural नगरपालिका' WHERE id = 40709;
UPDATE locations SET name_ne = 'Harinas Rural नगरपालिका' WHERE id = 40710;
UPDATE locations SET name_ne = 'Biruwa Rural नगरपालिका' WHERE id = 40711;
UPDATE locations SET name_ne = 'Bhanu नगरपालिका' WHERE id = 40801;
UPDATE locations SET name_ne = 'Bhimad नगरपालिका' WHERE id = 40802;
UPDATE locations SET name_ne = 'Byas नगरपालिका' WHERE id = 40803;
UPDATE locations SET name_ne = 'Shuklagandaki नगरपालिका' WHERE id = 40804;
UPDATE locations SET name_ne = 'Anbu Khaireni Rural नगरपालिका' WHERE id = 40805;
UPDATE locations SET name_ne = 'Devghat Rural नगरपालिका' WHERE id = 40806;
UPDATE locations SET name_ne = 'Bandipur Rural नगरपालिका' WHERE id = 40807;
UPDATE locations SET name_ne = 'Rishing Rural नगरपालिका' WHERE id = 40808;
UPDATE locations SET name_ne = 'Ghiring Rural नगरपालिका' WHERE id = 40809;
UPDATE locations SET name_ne = 'Myagde Rural नगरपालिका' WHERE id = 40810;
UPDATE locations SET name_ne = 'Kushma नगरपालिका' WHERE id = 40901;
UPDATE locations SET name_ne = 'Phalewas नगरपालिका' WHERE id = 40902;
UPDATE locations SET name_ne = 'Jaljala Rural नगरपालिका' WHERE id = 40903;
UPDATE locations SET name_ne = 'Paiyun Rural नगरपालिका' WHERE id = 40904;
UPDATE locations SET name_ne = 'Mahashila Rural नगरपालिका' WHERE id = 40905;
UPDATE locations SET name_ne = 'Modi Rural नगरपालिका' WHERE id = 40906;
UPDATE locations SET name_ne = 'Bihadi Rural नगरपालिका' WHERE id = 40907;
UPDATE locations SET name_ne = 'Baglung नगरपालिका' WHERE id = 41001;
UPDATE locations SET name_ne = 'Dhorpatan नगरपालिका' WHERE id = 41002;
UPDATE locations SET name_ne = 'Galkot नगरपालिका' WHERE id = 41003;
UPDATE locations SET name_ne = 'Jaimuni नगरपालिका' WHERE id = 41004;
UPDATE locations SET name_ne = 'Bareng Rural नगरपालिका' WHERE id = 41005;
UPDATE locations SET name_ne = 'Kathekhola Rural नगरपालिका' WHERE id = 41006;
UPDATE locations SET name_ne = 'Taman Khola Rural नगरपालिका' WHERE id = 41007;
UPDATE locations SET name_ne = 'Tara Khola Rural नगरपालिका' WHERE id = 41008;
UPDATE locations SET name_ne = 'Nisikhola Rural नगरपालिका' WHERE id = 41009;
UPDATE locations SET name_ne = 'Badigad Rural नगरपालिका' WHERE id = 41010;
UPDATE locations SET name_ne = 'Beni नगरपालिका' WHERE id = 41101;
UPDATE locations SET name_ne = 'Annapurna Rural नगरपालिका' WHERE id = 41102;
UPDATE locations SET name_ne = 'Dhaulagiri Rural नगरपालिका' WHERE id = 41103;
UPDATE locations SET name_ne = 'Mangala Rural नगरपालिका' WHERE id = 41104;
UPDATE locations SET name_ne = 'Malika Rural नगरपालिका' WHERE id = 41105;
UPDATE locations SET name_ne = 'Raghuganga Rural नगरपालिका' WHERE id = 41106;
UPDATE locations SET name_ne = 'Musikot नगरपालिका' WHERE id = 50101;
UPDATE locations SET name_ne = 'Resunga नगरपालिका' WHERE id = 50102;
UPDATE locations SET name_ne = 'Isma Rural नगरपालिका' WHERE id = 50103;
UPDATE locations SET name_ne = 'Kaligandaki Rural नगरपालिका' WHERE id = 50104;
UPDATE locations SET name_ne = 'Satyawati Rural नगरपालिका' WHERE id = 50105;
UPDATE locations SET name_ne = 'Chandrakot Rural नगरपालिका' WHERE id = 50106;
UPDATE locations SET name_ne = 'Ruru Rural नगरपालिका' WHERE id = 50107;
UPDATE locations SET name_ne = 'Chhatrakot Rural नगरपालिका' WHERE id = 50108;
UPDATE locations SET name_ne = 'Dhurkot Rural नगरपालिका' WHERE id = 50109;
UPDATE locations SET name_ne = 'Madane Rural नगरपालिका' WHERE id = 50110;
UPDATE locations SET name_ne = 'Malika Rural नगरपालिका' WHERE id = 50111;
UPDATE locations SET name_ne = 'Gulmi Darbar Rural नगरपालिका' WHERE id = 50112;
UPDATE locations SET name_ne = 'तानसेन नगरपालिका' WHERE id = 50201;
UPDATE locations SET name_ne = 'Rampur नगरपालिका' WHERE id = 50202;
UPDATE locations SET name_ne = 'Rainadevi Chhahara Rural नगरपालिका' WHERE id = 50203;
UPDATE locations SET name_ne = 'Ribdikot Rural नगरपालिका' WHERE id = 50204;
UPDATE locations SET name_ne = 'Purbakhola Rural नगरपालिका' WHERE id = 50205;
UPDATE locations SET name_ne = 'Rambha Rural नगरपालिका' WHERE id = 50206;
UPDATE locations SET name_ne = 'Tinahu Rural नगरपालिका' WHERE id = 50207;
UPDATE locations SET name_ne = 'Nisdi Rural नगरपालिका' WHERE id = 50208;
UPDATE locations SET name_ne = 'Mathagadhi Rural नगरपालिका' WHERE id = 50209;
UPDATE locations SET name_ne = 'Bagnaskali Rural नगरपालिका' WHERE id = 50210;
UPDATE locations SET name_ne = 'बुटवल उप-महानगरपालिका' WHERE id = 50301;
UPDATE locations SET name_ne = 'Devdaha नगरपालिका' WHERE id = 50302;
UPDATE locations SET name_ne = 'Lumbini Sanskritik नगरपालिका' WHERE id = 50303;
UPDATE locations SET name_ne = 'Sainamaina नगरपालिका' WHERE id = 50304;
UPDATE locations SET name_ne = 'सिद्धार्थनगर नगरपालिका' WHERE id = 50305;
UPDATE locations SET name_ne = 'Tilottama नगरपालिका' WHERE id = 50306;
UPDATE locations SET name_ne = 'Gaidahawa Rural नगरपालिका' WHERE id = 50307;
UPDATE locations SET name_ne = 'Kanchan Rural नगरपालिका' WHERE id = 50308;
UPDATE locations SET name_ne = 'Kotahimai Rural नगरपालिका' WHERE id = 50309;
UPDATE locations SET name_ne = 'Marchawari Rural नगरपालिका' WHERE id = 50310;
UPDATE locations SET name_ne = 'Mayadevi Rural नगरपालिका' WHERE id = 50311;
UPDATE locations SET name_ne = 'Omsatiya Rural नगरपालिका' WHERE id = 50312;
UPDATE locations SET name_ne = 'Rohini Rural नगरपालिका' WHERE id = 50313;
UPDATE locations SET name_ne = 'Sammarimai Rural नगरपालिका' WHERE id = 50314;
UPDATE locations SET name_ne = 'Siyari Rural नगरपालिका' WHERE id = 50315;
UPDATE locations SET name_ne = 'Suddhodhan Rural नगरपालिका' WHERE id = 50316;
UPDATE locations SET name_ne = 'Kapilvastu नगरपालिका' WHERE id = 50401;
UPDATE locations SET name_ne = 'Banganga नगरपालिका' WHERE id = 50402;
UPDATE locations SET name_ne = 'Buddhabhumi नगरपालिका' WHERE id = 50403;
UPDATE locations SET name_ne = 'Shivaraj नगरपालिका' WHERE id = 50404;
UPDATE locations SET name_ne = 'Krishnanagar नगरपालिका' WHERE id = 50405;
UPDATE locations SET name_ne = 'Maharajgunj नगरपालिका' WHERE id = 50406;
UPDATE locations SET name_ne = 'Mayadevi Rural नगरपालिका' WHERE id = 50407;
UPDATE locations SET name_ne = 'Yashodhara Rural नगरपालिका' WHERE id = 50408;
UPDATE locations SET name_ne = 'Suddhodhan Rural नगरपालिका' WHERE id = 50409;
UPDATE locations SET name_ne = 'Bijayanagar Rural नगरपालिका' WHERE id = 50410;
UPDATE locations SET name_ne = 'Sandhikharka नगरपालिका' WHERE id = 50501;
UPDATE locations SET name_ne = 'Sitganga नगरपालिका' WHERE id = 50502;
UPDATE locations SET name_ne = 'Bhumikasthan नगरपालिका' WHERE id = 50503;
UPDATE locations SET name_ne = 'Chhatradev Rural नगरपालिका' WHERE id = 50504;
UPDATE locations SET name_ne = 'Panini Rural नगरपालिका' WHERE id = 50505;
UPDATE locations SET name_ne = 'Malarani Rural नगरपालिका' WHERE id = 50506;
UPDATE locations SET name_ne = 'Pyuthan नगरपालिका' WHERE id = 50601;
UPDATE locations SET name_ne = 'Sworgadwari नगरपालिका' WHERE id = 50602;
UPDATE locations SET name_ne = 'Mandavi Rural नगरपालिका' WHERE id = 50603;
UPDATE locations SET name_ne = 'Mallarani Rural नगरपालिका' WHERE id = 50604;
UPDATE locations SET name_ne = 'Sarumarani Rural नगरपालिका' WHERE id = 50605;
UPDATE locations SET name_ne = 'Jhimruk Rural नगरपालिका' WHERE id = 50606;
UPDATE locations SET name_ne = 'Airawati Rural नगरपालिका' WHERE id = 50607;
UPDATE locations SET name_ne = 'Gaumukhi Rural नगरपालिका' WHERE id = 50608;
UPDATE locations SET name_ne = 'Naubahini Rural नगरपालिका' WHERE id = 50609;
UPDATE locations SET name_ne = 'Rolpa नगरपालिका' WHERE id = 50701;
UPDATE locations SET name_ne = 'Runtigadhi Rural नगरपालिका' WHERE id = 50702;
UPDATE locations SET name_ne = 'Triveni Rural नगरपालिका' WHERE id = 50703;
UPDATE locations SET name_ne = 'Sunil Smriti Rural नगरपालिका' WHERE id = 50704;
UPDATE locations SET name_ne = 'Lungri Rural नगरपालिका' WHERE id = 50705;
UPDATE locations SET name_ne = 'Sunchhahari Rural नगरपालिका' WHERE id = 50706;
UPDATE locations SET name_ne = 'Thawang Rural नगरपालिका' WHERE id = 50707;
UPDATE locations SET name_ne = 'Madi Rural नगरपालिका' WHERE id = 50708;
UPDATE locations SET name_ne = 'Gangadev Rural नगरपालिका' WHERE id = 50709;
UPDATE locations SET name_ne = 'Pariwartan Rural नगरपालिका' WHERE id = 50710;
UPDATE locations SET name_ne = 'Bhume Rural नगरपालिका' WHERE id = 50801;
UPDATE locations SET name_ne = 'Sisne Rural नगरपालिका' WHERE id = 50802;
UPDATE locations SET name_ne = 'Putha Uttarganga Rural नगरपालिका' WHERE id = 50803;
UPDATE locations SET name_ne = 'नेपालगञ्ज उप-महानगरपालिका' WHERE id = 50901;
UPDATE locations SET name_ne = 'Kohalpur नगरपालिका' WHERE id = 50902;
UPDATE locations SET name_ne = 'Rapti Sonari Rural नगरपालिका' WHERE id = 50903;
UPDATE locations SET name_ne = 'Narainapur Rural नगरपालिका' WHERE id = 50904;
UPDATE locations SET name_ne = 'Duduwa Rural नगरपालिका' WHERE id = 50905;
UPDATE locations SET name_ne = 'Janaki Rural नगरपालिका' WHERE id = 50906;
UPDATE locations SET name_ne = 'Khajura Rural नगरपालिका' WHERE id = 50907;
UPDATE locations SET name_ne = 'Baijnath Rural नगरपालिका' WHERE id = 50908;
UPDATE locations SET name_ne = 'गुलरिया नगरपालिका' WHERE id = 51001;
UPDATE locations SET name_ne = 'Madhuwan नगरपालिका' WHERE id = 51002;
UPDATE locations SET name_ne = 'Rajapur नगरपालिका' WHERE id = 51003;
UPDATE locations SET name_ne = 'Thakurbaba नगरपालिका' WHERE id = 51004;
UPDATE locations SET name_ne = 'Bansagadhi नगरपालिका' WHERE id = 51005;
UPDATE locations SET name_ne = 'Barbardiya नगरपालिका' WHERE id = 51006;
UPDATE locations SET name_ne = 'Badhaiyatal Rural नगरपालिका' WHERE id = 51007;
UPDATE locations SET name_ne = 'Geruwa Rural नगरपालिका' WHERE id = 51008;
UPDATE locations SET name_ne = 'घोराही उप-महानगरपालिका' WHERE id = 51101;
UPDATE locations SET name_ne = 'तुलसीपुर उप-महानगरपालिका' WHERE id = 51102;
UPDATE locations SET name_ne = 'Lamahi नगरपालिका' WHERE id = 51103;
UPDATE locations SET name_ne = 'Gadhawa Rural नगरपालिका' WHERE id = 51104;
UPDATE locations SET name_ne = 'Rajpur Rural नगरपालिका' WHERE id = 51105;
UPDATE locations SET name_ne = 'Shantinagar Rural नगरपालिका' WHERE id = 51106;
UPDATE locations SET name_ne = 'Rapti Rural नगरपालिका' WHERE id = 51107;
UPDATE locations SET name_ne = 'Banglachuli Rural नगरपालिका' WHERE id = 51108;
UPDATE locations SET name_ne = 'Dangisharan Rural नगरपालिका' WHERE id = 51109;
UPDATE locations SET name_ne = 'Babai Rural नगरपालिका' WHERE id = 51110;
UPDATE locations SET name_ne = 'Bardaghat नगरपालिका' WHERE id = 51201;
UPDATE locations SET name_ne = 'Ramgram नगरपालिका' WHERE id = 51202;
UPDATE locations SET name_ne = 'Sunwal नगरपालिका' WHERE id = 51203;
UPDATE locations SET name_ne = 'Susta Rural नगरपालिका' WHERE id = 51204;
UPDATE locations SET name_ne = 'Palhinandan Rural नगरपालिका' WHERE id = 51205;
UPDATE locations SET name_ne = 'Pratappur Rural नगरपालिका' WHERE id = 51206;
UPDATE locations SET name_ne = 'Sarawal Rural नगरपालिका' WHERE id = 51207;
UPDATE locations SET name_ne = 'Musikot नगरपालिका' WHERE id = 60101;
UPDATE locations SET name_ne = 'Chaurjahari नगरपालिका' WHERE id = 60102;
UPDATE locations SET name_ne = 'Aathbiskot नगरपालिका' WHERE id = 60103;
UPDATE locations SET name_ne = 'Banphikot Rural नगरपालिका' WHERE id = 60104;
UPDATE locations SET name_ne = 'Tribeni Rural नगरपालिका' WHERE id = 60105;
UPDATE locations SET name_ne = 'Sani Bheri Rural नगरपालिका' WHERE id = 60106;
UPDATE locations SET name_ne = 'Bagchaur नगरपालिका' WHERE id = 60201;
UPDATE locations SET name_ne = 'Bangad Kupinde नगरपालिका' WHERE id = 60202;
UPDATE locations SET name_ne = 'Shaarda नगरपालिका' WHERE id = 60203;
UPDATE locations SET name_ne = 'Kalimati Rural नगरपालिका' WHERE id = 60204;
UPDATE locations SET name_ne = 'Tribeni Rural नगरपालिका' WHERE id = 60205;
UPDATE locations SET name_ne = 'Kapurkot Rural नगरपालिका' WHERE id = 60206;
UPDATE locations SET name_ne = 'Chhatreshwari Rural नगरपालिका' WHERE id = 60207;
UPDATE locations SET name_ne = 'Kumakh Rural नगरपालिका' WHERE id = 60208;
UPDATE locations SET name_ne = 'Siddha Kumakh Rural नगरपालिका' WHERE id = 60209;
UPDATE locations SET name_ne = 'Darma Rural नगरपालिका' WHERE id = 60210;
UPDATE locations SET name_ne = 'Thuli Bheri नगरपालिका' WHERE id = 60301;
UPDATE locations SET name_ne = 'Tripurasundari नगरपालिका' WHERE id = 60302;
UPDATE locations SET name_ne = 'Dolpo Buddha Rural नगरपालिका' WHERE id = 60303;
UPDATE locations SET name_ne = 'She Phoksundo Rural नगरपालिका' WHERE id = 60304;
UPDATE locations SET name_ne = 'Jagadulla Rural नगरपालिका' WHERE id = 60305;
UPDATE locations SET name_ne = 'Mudkechula Rural नगरपालिका' WHERE id = 60306;
UPDATE locations SET name_ne = 'Kaike Rural नगरपालिका' WHERE id = 60307;
UPDATE locations SET name_ne = 'Chharka Tangsong Rural नगरपालिका' WHERE id = 60308;
UPDATE locations SET name_ne = 'Simkot Rural नगरपालिका' WHERE id = 60401;
UPDATE locations SET name_ne = 'Namkha Rural नगरपालिका' WHERE id = 60402;
UPDATE locations SET name_ne = 'Kharpunath Rural नगरपालिका' WHERE id = 60403;
UPDATE locations SET name_ne = 'Sarkegad Rural नगरपालिका' WHERE id = 60404;
UPDATE locations SET name_ne = 'Chankheli Rural नगरपालिका' WHERE id = 60405;
UPDATE locations SET name_ne = 'Adanchuli Rural नगरपालिका' WHERE id = 60406;
UPDATE locations SET name_ne = 'Tanjakot Rural नगरपालिका' WHERE id = 60407;
UPDATE locations SET name_ne = 'Chandannath नगरपालिका' WHERE id = 60501;
UPDATE locations SET name_ne = 'Kanakasundari Rural नगरपालिका' WHERE id = 60502;
UPDATE locations SET name_ne = 'Sinja Rural नगरपालिका' WHERE id = 60503;
UPDATE locations SET name_ne = 'Hima Rural नगरपालिका' WHERE id = 60504;
UPDATE locations SET name_ne = 'Tila Rural नगरपालिका' WHERE id = 60505;
UPDATE locations SET name_ne = 'Guthichaur Rural नगरपालिका' WHERE id = 60506;
UPDATE locations SET name_ne = 'Tatopani Rural नगरपालिका' WHERE id = 60507;
UPDATE locations SET name_ne = 'Patarasi Rural नगरपालिका' WHERE id = 60508;
UPDATE locations SET name_ne = 'Khandachakra नगरपालिका' WHERE id = 60601;
UPDATE locations SET name_ne = 'Raskot नगरपालिका' WHERE id = 60602;
UPDATE locations SET name_ne = 'Tilagufa नगरपालिका' WHERE id = 60603;
UPDATE locations SET name_ne = 'Pachaljharana Rural नगरपालिका' WHERE id = 60604;
UPDATE locations SET name_ne = 'Sanni Triveni Rural नगरपालिका' WHERE id = 60605;
UPDATE locations SET name_ne = 'Narharinath Rural नगरपालिका' WHERE id = 60606;
UPDATE locations SET name_ne = 'Shubha Kalika Rural नगरपालिका' WHERE id = 60607;
UPDATE locations SET name_ne = 'Mahawai Rural नगरपालिका' WHERE id = 60608;
UPDATE locations SET name_ne = 'Palata Rural नगरपालिका' WHERE id = 60609;
UPDATE locations SET name_ne = 'Chhayanath Rara नगरपालिका' WHERE id = 60701;
UPDATE locations SET name_ne = 'Mugum Karmarong Rural नगरपालिका' WHERE id = 60702;
UPDATE locations SET name_ne = 'Soru Rural नगरपालिका' WHERE id = 60703;
UPDATE locations SET name_ne = 'Khatyad Rural नगरपालिका' WHERE id = 60704;
UPDATE locations SET name_ne = 'वीरेन्द्रनगर नगरपालिका' WHERE id = 60801;
UPDATE locations SET name_ne = 'Bheriganga नगरपालिका' WHERE id = 60802;
UPDATE locations SET name_ne = 'Gurbhakot नगरपालिका' WHERE id = 60803;
UPDATE locations SET name_ne = 'Panchapuri नगरपालिका' WHERE id = 60804;
UPDATE locations SET name_ne = 'Lekbesi नगरपालिका' WHERE id = 60805;
UPDATE locations SET name_ne = 'Chaukune Rural नगरपालिका' WHERE id = 60806;
UPDATE locations SET name_ne = 'Barahatal Rural नगरपालिका' WHERE id = 60807;
UPDATE locations SET name_ne = 'Chingad Rural नगरपालिका' WHERE id = 60808;
UPDATE locations SET name_ne = 'Simta Rural नगरपालिका' WHERE id = 60809;
UPDATE locations SET name_ne = 'Narayan नगरपालिका' WHERE id = 60901;
UPDATE locations SET name_ne = 'Dullu नगरपालिका' WHERE id = 60902;
UPDATE locations SET name_ne = 'Chamunda Bindrasaini नगरपालिका' WHERE id = 60903;
UPDATE locations SET name_ne = 'Aathbis नगरपालिका' WHERE id = 60904;
UPDATE locations SET name_ne = 'Bhagawatimai Rural नगरपालिका' WHERE id = 60905;
UPDATE locations SET name_ne = 'Gurans Rural नगरपालिका' WHERE id = 60906;
UPDATE locations SET name_ne = 'Dungeshwor Rural नगरपालिका' WHERE id = 60907;
UPDATE locations SET name_ne = 'Naumule Rural नगरपालिका' WHERE id = 60908;
UPDATE locations SET name_ne = 'Mahabu Rural नगरपालिका' WHERE id = 60909;
UPDATE locations SET name_ne = 'Bhairabi Rural नगरपालिका' WHERE id = 60910;
UPDATE locations SET name_ne = 'Thantikandh Rural नगरपालिका' WHERE id = 60911;
UPDATE locations SET name_ne = 'Bheri नगरपालिका' WHERE id = 61001;
UPDATE locations SET name_ne = 'Chhedagad नगरपालिका' WHERE id = 61002;
UPDATE locations SET name_ne = 'Nalgad नगरपालिका' WHERE id = 61003;
UPDATE locations SET name_ne = 'Junichande Rural नगरपालिका' WHERE id = 61004;
UPDATE locations SET name_ne = 'Kuse Rural नगरपालिका' WHERE id = 61005;
UPDATE locations SET name_ne = 'Barekot Rural नगरपालिका' WHERE id = 61006;
UPDATE locations SET name_ne = 'Shivalaya Rural नगरपालिका' WHERE id = 61007;
UPDATE locations SET name_ne = 'धनगढी उप-महानगरपालिका' WHERE id = 70101;
UPDATE locations SET name_ne = 'टीकापुर नगरपालिका' WHERE id = 70102;
UPDATE locations SET name_ne = 'Ghodaghodi नगरपालिका' WHERE id = 70103;
UPDATE locations SET name_ne = 'Lamkichuha नगरपालिका' WHERE id = 70104;
UPDATE locations SET name_ne = 'Bhajani नगरपालिका' WHERE id = 70105;
UPDATE locations SET name_ne = 'Godawari नगरपालिका' WHERE id = 70106;
UPDATE locations SET name_ne = 'Gauriganga नगरपालिका' WHERE id = 70107;
UPDATE locations SET name_ne = 'Janaki Rural नगरपालिका' WHERE id = 70108;
UPDATE locations SET name_ne = 'Bardagoriya Rural नगरपालिका' WHERE id = 70109;
UPDATE locations SET name_ne = 'Mohanyal Rural नगरपालिका' WHERE id = 70110;
UPDATE locations SET name_ne = 'Kailari Rural नगरपालिका' WHERE id = 70111;
UPDATE locations SET name_ne = 'Joshipur Rural नगरपालिका' WHERE id = 70112;
UPDATE locations SET name_ne = 'Chure Rural नगरपालिका' WHERE id = 70113;
UPDATE locations SET name_ne = 'Bhimdatta नगरपालिका' WHERE id = 70201;
UPDATE locations SET name_ne = 'Punarbas नगरपालिका' WHERE id = 70202;
UPDATE locations SET name_ne = 'Bedkot नगरपालिका' WHERE id = 70203;
UPDATE locations SET name_ne = 'Mahakali नगरपालिका' WHERE id = 70204;
UPDATE locations SET name_ne = 'Shuklaphanta नगरपालिका' WHERE id = 70205;
UPDATE locations SET name_ne = 'Belauri नगरपालिका' WHERE id = 70206;
UPDATE locations SET name_ne = 'Krishnapur नगरपालिका' WHERE id = 70207;
UPDATE locations SET name_ne = 'Beldandi Rural नगरपालिका' WHERE id = 70208;
UPDATE locations SET name_ne = 'Laljhadi Rural नगरपालिका' WHERE id = 70209;
UPDATE locations SET name_ne = 'Amargadhi नगरपालिका' WHERE id = 70301;
UPDATE locations SET name_ne = 'Parshuram नगरपालिका' WHERE id = 70302;
UPDATE locations SET name_ne = 'Aalitaal Rural नगरपालिका' WHERE id = 70303;
UPDATE locations SET name_ne = 'Bhageshwar Rural नगरपालिका' WHERE id = 70304;
UPDATE locations SET name_ne = 'Navadurga Rural नगरपालिका' WHERE id = 70305;
UPDATE locations SET name_ne = 'Ajaymeru Rural नगरपालिका' WHERE id = 70306;
UPDATE locations SET name_ne = 'Ganyapdhura Rural नगरपालिका' WHERE id = 70307;
UPDATE locations SET name_ne = 'Dasharathchand नगरपालिका' WHERE id = 70401;
UPDATE locations SET name_ne = 'Patan नगरपालिका' WHERE id = 70402;
UPDATE locations SET name_ne = 'Melauli नगरपालिका' WHERE id = 70403;
UPDATE locations SET name_ne = 'Purchaudi नगरपालिका' WHERE id = 70404;
UPDATE locations SET name_ne = 'Surnaya Rural नगरपालिका' WHERE id = 70405;
UPDATE locations SET name_ne = 'Sigas Rural नगरपालिका' WHERE id = 70406;
UPDATE locations SET name_ne = 'Shivanath Rural नगरपालिका' WHERE id = 70407;
UPDATE locations SET name_ne = 'Pancheshwar Rural नगरपालिका' WHERE id = 70408;
UPDATE locations SET name_ne = 'Dogdakedar Rural नगरपालिका' WHERE id = 70409;
UPDATE locations SET name_ne = 'Dilasaini Rural नगरपालिका' WHERE id = 70410;
UPDATE locations SET name_ne = 'Dipayal Silgadhi नगरपालिका' WHERE id = 70501;
UPDATE locations SET name_ne = 'Shikhar नगरपालिका' WHERE id = 70502;
UPDATE locations SET name_ne = 'Purbichauki Rural नगरपालिका' WHERE id = 70503;
UPDATE locations SET name_ne = 'Badikedar Rural नगरपालिका' WHERE id = 70504;
UPDATE locations SET name_ne = 'Jorayal Rural नगरपालिका' WHERE id = 70505;
UPDATE locations SET name_ne = 'Sayal Rural नगरपालिका' WHERE id = 70506;
UPDATE locations SET name_ne = 'Aadarsha Rural नगरपालिका' WHERE id = 70507;
UPDATE locations SET name_ne = 'K I Singh Rural नगरपालिका' WHERE id = 70508;
UPDATE locations SET name_ne = 'Bogtan Rural नगरपालिका' WHERE id = 70509;
UPDATE locations SET name_ne = 'Mangalsen नगरपालिका' WHERE id = 70601;
UPDATE locations SET name_ne = 'Kamalbazar नगरपालिका' WHERE id = 70602;
UPDATE locations SET name_ne = 'Sanphebagar नगरपालिका' WHERE id = 70603;
UPDATE locations SET name_ne = 'Panchadewal Binayak नगरपालिका' WHERE id = 70604;
UPDATE locations SET name_ne = 'Chaurpati Rural नगरपालिका' WHERE id = 70605;
UPDATE locations SET name_ne = 'Mellekh Rural नगरपालिका' WHERE id = 70606;
UPDATE locations SET name_ne = 'Bannigadhi Jayagadh Rural नगरपालिका' WHERE id = 70607;
UPDATE locations SET name_ne = 'Ramaroshan Rural नगरपालिका' WHERE id = 70608;
UPDATE locations SET name_ne = 'Dhakari Rural नगरपालिका' WHERE id = 70609;
UPDATE locations SET name_ne = 'Turmakhand Rural नगरपालिका' WHERE id = 70610;
UPDATE locations SET name_ne = 'Jaya Prithvi नगरपालिका' WHERE id = 70701;
UPDATE locations SET name_ne = 'Bungal नगरपालिका' WHERE id = 70702;
UPDATE locations SET name_ne = 'Talkot Rural नगरपालिका' WHERE id = 70703;
UPDATE locations SET name_ne = 'Masta Rural नगरपालिका' WHERE id = 70704;
UPDATE locations SET name_ne = 'Khaptadchhanna Rural नगरपालिका' WHERE id = 70705;
UPDATE locations SET name_ne = 'Thalara Rural नगरपालिका' WHERE id = 70706;
UPDATE locations SET name_ne = 'Bitthadchir Rural नगरपालिका' WHERE id = 70707;
UPDATE locations SET name_ne = 'Surma Rural नगरपालिका' WHERE id = 70708;
UPDATE locations SET name_ne = 'Chhabis Pathibhera Rural नगरपालिका' WHERE id = 70709;
UPDATE locations SET name_ne = 'Durgathali Rural नगरपालिका' WHERE id = 70710;
UPDATE locations SET name_ne = 'Kedarsyu Rural नगरपालिका' WHERE id = 70711;
UPDATE locations SET name_ne = 'Saipal Rural नगरपालिका' WHERE id = 70712;
UPDATE locations SET name_ne = 'Badimalika नगरपालिका' WHERE id = 70801;
UPDATE locations SET name_ne = 'Triveni नगरपालिका' WHERE id = 70802;
UPDATE locations SET name_ne = 'Budhiganga नगरपालिका' WHERE id = 70803;
UPDATE locations SET name_ne = 'Budhinanda नगरपालिका' WHERE id = 70804;
UPDATE locations SET name_ne = 'Gaumul Rural नगरपालिका' WHERE id = 70805;
UPDATE locations SET name_ne = 'Jagannath Rural नगरपालिका' WHERE id = 70806;
UPDATE locations SET name_ne = 'Swamikartik Khapar Rural नगरपालिका' WHERE id = 70807;
UPDATE locations SET name_ne = 'Khaptad Chhededaha Rural नगरपालिका' WHERE id = 70808;
UPDATE locations SET name_ne = 'Himali Rural नगरपालिका' WHERE id = 70809;
UPDATE locations SET name_ne = 'Shailyashikhar नगरपालिका' WHERE id = 70901;
UPDATE locations SET name_ne = 'Mahakali नगरपालिका' WHERE id = 70902;
UPDATE locations SET name_ne = 'Malikarjun Rural नगरपालिका' WHERE id = 70903;
UPDATE locations SET name_ne = 'Apihimal Rural नगरपालिका' WHERE id = 70904;
UPDATE locations SET name_ne = 'Duhun Rural नगरपालिका' WHERE id = 70905;
UPDATE locations SET name_ne = 'Naugad Rural नगरपालिका' WHERE id = 70906;
UPDATE locations SET name_ne = 'Marma Rural नगरपालिका' WHERE id = 70907;
UPDATE locations SET name_ne = 'Lekam Rural नगरपालिका' WHERE id = 70908;
UPDATE locations SET name_ne = 'Byans Rural नगरपालिका' WHERE id = 70909;
UPDATE locations SET name_ne = 'कोशी प्रदेश' WHERE id = 1;
UPDATE locations SET name_ne = 'मधेश प्रदेश' WHERE id = 2;
UPDATE locations SET name_ne = 'बागमती प्रदेश' WHERE id = 3;
UPDATE locations SET name_ne = 'गण्डकी प्रदेश' WHERE id = 4;
UPDATE locations SET name_ne = 'लुम्बिनी प्रदेश' WHERE id = 5;
UPDATE locations SET name_ne = 'कर्णाली प्रदेश' WHERE id = 6;
UPDATE locations SET name_ne = 'सुदूरपश्चिम प्रदेश' WHERE id = 7;

-- Updated: 921, Skipped: 0